# Generated by Django 5.2.5 on 2025-09-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uauth', '0002_oauthaccount_oauth_accou_user_id_9d8b45_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='profile_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]

