# Generated by Django 5.2.5 on 2025-08-21 11:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteImage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('note_name', models.CharField(blank=True, max_length=50, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'images',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'conversations',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('system', 'system'), ('user', 'user'), ('assistant', 'assistant')], max_length=20)),
                ('content', models.TextField()),
                ('model', models.CharField(blank=True, max_length=120, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='scentpick.conversation')),
            ],
            options={
                'db_table': 'messages',
            },
        ),
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('eng_name', models.CharField(max_length=100)),
                ('size_ml', models.DecimalField(decimal_places=1, help_text='(ml)', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('price_krw', models.IntegerField(blank=True, null=True)),
                ('detail_url', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('concentration', models.CharField(blank=True, max_length=30, null=True)),
                ('main_accords', models.TextField(blank=True, null=True)),
                ('top_notes', models.TextField(blank=True, null=True)),
                ('middle_notes', models.TextField(blank=True, null=True)),
                ('base_notes', models.TextField(blank=True, null=True)),
                ('notes_score', models.TextField(blank=True, null=True)),
                ('season_score', models.TextField(blank=True, null=True)),
                ('day_night_score', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'perfumes',
                'indexes': [models.Index(fields=['brand'], name='perfumes_brand_ab6905_idx'), models.Index(fields=['name'], name='perfumes_name_d46302_idx'), models.Index(fields=['eng_name'], name='perfumes_eng_nam_909033_idx')],
                'constraints': [models.UniqueConstraint(fields=('brand', 'name', 'eng_name', 'size_ml'), name='uq_perfume_brand_name_eng_size_ml')],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='scentpick.perfume')),
            ],
            options={
                'db_table': 'favorites',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='scentpick.perfume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ratings',
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user'], name='conversatio_user_id_0d3af7_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['updated_at'], name='conversatio_updated_8d1310_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='messages_convers_3ebb41_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user'], name='favorites_user_id_bc3324_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['perfume'], name='favorites_perfume_ec78ea_idx'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'perfume'), name='uq_favorite_user_perfume'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['perfume'], name='ratings_perfume_1cf95b_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['user'], name='ratings_user_id_bd9bb9_idx'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('user', 'perfume'), name='uq_rating_user_perfume'),
        ),
    ]
