# Generated by Django 5.2.5 on 2025-09-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scentpick', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='base_notes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='main_accords',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='middle_notes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='top_notes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
