# Generated by Django 5.2.6 on 2025-09-11 02:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scentpick', '0002_alter_perfume_base_notes_alter_perfume_main_accords_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='external_thread_id',
            field=models.CharField(blank=True, db_index=True, help_text='FastAPI/LangGraph thread_id (예: UUID)', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='state',
            field=models.JSONField(blank=True, help_text='LangGraph state snapshot', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='tool_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='recrun',
            name='query_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['external_thread_id'], name='conversatio_externa_1a58d3_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['idempotency_key'], name='messages_idempot_5f6392_idx'),
        ),
    ]
