# Generated by Django 5.2.6 on 2025-09-11 03:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scentpick', '0003_conversation_external_thread_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='conversation',
            name='conversatio_externa_1a58d3_idx',
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('external_thread_id',), name='uniq_conversations_external_thread_id'),
        ),
    ]
