# Generated by Django 5.2.5 on 2025-09-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scentpick', '0004_remove_conversation_conversatio_externa_1a58d3_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='chat_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
