# Generated by Django 5.2.6 on 2025-09-04 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scentpick', '0002_alter_perfume_base_notes_alter_perfume_main_accords_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfume',
            options={'ordering': ['id']},
        ),
    ]
