# Generated by Django 5.2.5 on 2025-09-02 05:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uauth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='oauthaccount',
            index=models.Index(fields=['user'], name='oauth_accou_user_id_9d8b45_idx'),
        ),
        migrations.AddIndex(
            model_name='userdetail',
            index=models.Index(fields=['created_at'], name='users_created_6541e9_idx'),
        ),
    ]
