# Generated by Django 5.2.4 on 2025-09-03 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='브랜드')),
                ('name', models.CharField(max_length=200, verbose_name='향수명')),
                ('detail_url', models.URLField(blank=True, null=True, verbose_name='상세 URL')),
                ('concentration', models.CharField(choices=[('오 드 퍼퓸', '오 드 퍼퓸 (EDP)'), ('오 드 뚜왈렛', '오 드 뚜왈렛 (EDT)'), ('오 드 코롱', '오 드 코롱 (EDC)'), ('퍼퓸', '퍼퓸 (Parfum)')], max_length=50, verbose_name='농도')),
                ('description', models.TextField(verbose_name='설명')),
                ('gender', models.CharField(choices=[('Male', '남성'), ('Female', '여성'), ('Unisex', '유니섹스')], max_length=10, verbose_name='성별')),
                ('main_accords', models.CharField(max_length=500, verbose_name='메인 어코드')),
                ('top_notes', models.CharField(max_length=500, verbose_name='톱 노트')),
                ('middle_notes', models.CharField(max_length=500, verbose_name='미들 노트')),
                ('base_notes', models.CharField(max_length=500, verbose_name='베이스 노트')),
                ('notes_score', models.TextField(help_text='JSON 형태', verbose_name='노트 점수')),
                ('season_score', models.TextField(help_text='JSON 형태', verbose_name='계절 점수')),
                ('day_night_score', models.TextField(help_text='JSON 형태', verbose_name='시간대 점수')),
                ('sizes', models.CharField(max_length=200, verbose_name='사이즈')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '향수',
                'verbose_name_plural': '향수들',
                'db_table': 'perfumes',
                'ordering': ['brand', 'name'],
            },
        ),
    ]
