# Generated by Django 5.2.4 on 2025-09-03 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spinner_tip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='perfume_images/', verbose_name='향수 이미지'),
        ),
        migrations.AddField(
            model_name='perfume',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='이미지 URL'),
        ),
    ]
