# Generated by Django 5.2.4 on 2025-09-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spinner_tip', '0002_perfume_image_perfume_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='카테고리')),
                ('note_name', models.CharField(max_length=200, verbose_name='노트명')),
                ('image_url', models.URLField(verbose_name='이미지 URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '노트 이미지',
                'verbose_name_plural': '노트 이미지들',
                'db_table': 'note_images',
                'ordering': ['category', 'note_name'],
                'unique_together': {('note_name', 'image_url')},
            },
        ),
    ]
