# Generated by Django 5.2.5 on 2025-09-09 03:26

from django.db import migrations, models


def add_profile_image_url_column(apps, schema_editor):
    """Add users.profile_image_url only if it doesn't already exist (MySQL 5.7 safe)."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT COUNT(*)
            FROM information_schema.COLUMNS
            WHERE TABLE_SCHEMA = DATABASE()
              AND TABLE_NAME = %s
              AND COLUMN_NAME = %s
            """,
            ["users", "profile_image_url"],
        )
        exists = cursor.fetchone()[0] > 0
        if not exists:
            cursor.execute(
                "ALTER TABLE `users` ADD COLUMN `profile_image_url` varchar(200) NULL"
            )


def drop_profile_image_url_column(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT COUNT(*)
            FROM information_schema.COLUMNS
            WHERE TABLE_SCHEMA = DATABASE()
              AND TABLE_NAME = %s
              AND COLUMN_NAME = %s
            """,
            ["users", "profile_image_url"],
        )
        exists = cursor.fetchone()[0] > 0
        if exists:
            cursor.execute(
                "ALTER TABLE `users` DROP COLUMN `profile_image_url`"
            )


class Migration(migrations.Migration):

    dependencies = [
        ('uauth', '0002_oauthaccount_oauth_accou_user_id_9d8b45_idx_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='userdetail',
                    name='profile_image_url',
                    field=models.URLField(blank=True, null=True),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    code=add_profile_image_url_column,
                    reverse_code=drop_profile_image_url_column,
                ),
            ],
        ),
        migrations.DeleteModel(
            name='OAuthAccount',
        ),
    ]
