detail_urls = [
    ('Aventus', 'https://www.fragrantica.com/perfume/Creed/Aventus-9828.html'),
    ('Eau Wood', 'https://www.fragrantica.com/perfume/Tom-Ford/Oud-Wood-Parfum-89988.html'),
    ('Tecit', 'https://www.fragrantica.com/perfume/Aesop/Tacit-32134.html'),
    ('Silver Mountain Water', 'https://www.fragrantica.com/perfume/Creed/Silver-Mountain-Water-472.html'),
    ('Moonlight in Heaven', 'https://www.fragrantica.com/perfume/By-Kilian/Moonlight-in-Heaven-35973.html'),
    ('Eau des Sens', 'https://www.fragrantica.com/perfume/Diptyque/Eau-des-Sens-Eau-de-Toilette-35678.html'),
    ('Mirto di Panarea', 'https://www.fragrantica.com/perfume/Acqua-di-Parma/Mirto-di-Panarea-La-Riserva-107111.html'),
    ('Fleur de Peau', 'https://www.fragrantica.com/perfume/Diptyque/Fleur-de-Peau-Eau-de-Parfum-48681.html'),
    ("Angel's Share", 'https://www.fragrantica.com/perfume/By-Kilian/Angels-Share-62615.html'),
    ('Blanche', 'https://www.fragrantica.com/perfume/Byredo/Blanche-6686.html'),
    ('Another 13', 'https://www.fragrantica.com/perfume/Le-Labo/Another-13-10131.html'),
    ('Lazy Sunday Morning', 'https://www.fragrantica.com/perfume/Maison-Martin-Margiela/Lazy-Sunday-Morning-20542.html'),
    ("Pico d'Amalfi", 'https://www.fragrantica.com/perfume/Rabanne/Paco-1487.html'),
    ('Portrait of a Lady', 'https://www.fragrantica.com/perfume/Frederic-Malle/Portrait-of-a-Lady-10464.html'),
    ('Black Orchid', 'https://www.fragrantica.com/perfume/Tom-Ford/Black-Orchid-1018.html'),
    ('Black Orchid', 'https://www.fragrantica.com/perfume/Tom-Ford/Black-Orchid-1018.html'),
    ('Orpheon', 'https://www.fragrantica.com/perfume/Diptyque/Orpheon-Eau-de-Parfum-65738.html'),
    ('Neroli Portofino', 'https://www.fragrantica.com/perfume/Tom-Ford/Neroli-Portofino-12192.html'),
    ('Bamboo Harmony', 'https://www.fragrantica.com/perfume/By-Kilian/Bamboo-Harmony-14330.html'),
    ('Good Girl Gone Bad', 'https://www.fragrantica.com/perfume/By-Kilian/Good-Girl-Gone-Bad-15924.html'),
    ('Gypsy Water', 'https://www.fragrantica.com/perfume/Byredo/Gypsy-Water-3575.html'),
    ("Val d'Afrique", 'https://www.fragrantica.com/perfume/Guerlain/Mon-Precious-Nectar-Fountain-Imperiale-11929.html'),
    ('Vetiver Extraordinaire', 'https://www.fragrantica.com/perfume/Frederic-Malle/Vetiver-Extraordinaire-4774.html'),
    ('Hyle', 'https://www.fragrantica.com/perfume/Farmacia-SS-Annunziata/Hyle-9568.html'),
    ('Te Noir 29', 'https://www.fragrantica.com/perfume/Le-Labo/The-Noir-29-Perfume-Oil-71926.html'),
    ('Fabulous', 'https://www.fragrantica.com/perfume/Victoria-s-Secret/Fabulous-17699.html'),
    ('White Suede Set', 'https://www.fragrantica.com/perfume/Calgon/Japanese-Cherry-Blossom-106655.html'),
    ('Jazz Club', 'https://www.fragrantica.com/perfume/Maison-Martin-Margiela/Jazz-Club-20541.html'),
    ('Black Phantom', 'https://www.fragrantica.com/perfume/By-Kilian/Black-Phantom-43632.html'),
    ('La Tulip', 'https://www.fragrantica.com/perfume/Byredo/La-Tulipe-8441.html'),
    ('Musk Lavageur', 'https://www.fragrantica.com/perfume/Frederic-Malle/Musc-Ravageur-1801.html'),
    ('Original Vetiver', 'https://www.fragrantica.com/perfume/Creed/Original-Vetiver-468.html'),
    ('Un Jardin sur Nil', 'https://www.fragrantica.com/perfume/Hermes/Un-Jardin-Sur-Le-Nil-18.html'),
    ('Mojave Ghost', 'https://www.fragrantica.com/perfume/Byredo/Mojave-Ghost-27040.html'),
    ('Santalle 33', 'https://www.fragrantica.com/perfume/Le-Labo/Santal-33-12201.html'),
    ('White Suede', 'https://www.fragrantica.com/perfume/Tom-Ford/White-Suede-6386.html'),
    ("Love Don't Be Chay", 'https://www.fragrantica.com/perfume/By-Kilian/Love-don-t-be-shy-Anniversary-Edition-77056.html'),
    ('Dawson', 'https://www.fragrantica.com/perfume/Hotel-Dawson/Roll-The-Dice-94829.html'),
    ('Not a Parfum', 'https://www.fragrantica.com/perfume/Histoires-de-Parfums/This-is-Not-a-Blue-Bottle-1-7-91868.html'),
    ("Lombre Dans L'eau", 'https://www.fragrantica.com/perfume/Diptyque/L-Ombre-Dans-L-Eau-Eau-de-Toilette-3962.html'),
    ('Eau Rose', 'https://www.fragrantica.com/perfume/Diptyque/Eau-Rose-14214.html'),
    ('X Vetiver', 'https://www.fragrantica.com/perfume/West-Third-Brand/Vetiver-X-41856.html'),
    ('Freesia', 'https://www.fragrantica.com/perfume/Jenny-Glow/Freesia-Pear-88785.html'),
    ('Sauvage', 'https://www.fragrantica.com/perfume/Dior/Sauvage-31861.html'),
    ('Aventus for Her', 'https://www.fragrantica.com/perfume/Creed/Aventus-for-Her-38497.html'),
    ('Bergamot 22', 'https://www.fragrantica.com/perfume/The-Dua-Brand/22-Shades-of-Bergamot-85702.html'),
    ('H24', 'https://www.fragrantica.com/perfume/Hermes/H24-65147.html'),
    ('Eude Wood Set', 'https://www.fragrantica.com/perfume/Solid-State/Supreme-111476.html'),
    ('724', 'https://www.fragrantica.com/perfume/Maison-Francis-Kurkdjian/724-75754.html'),
    ('Vireré', 'https://www.fragrantica.com/perfume/Aesop/Virere-96261.html'),
    ('Ethersis', 'https://www.fragrantica.com/perfume/Arman-Manoukian-Parfums/Cuir-Animalic-66778.html'),
    ('Ombré Leather', 'https://www.fragrantica.com/perfume/Tom-Ford/Ombre-Leather-2018-50239.html'),
    ('Philosykos', 'https://www.fragrantica.com/perfume/Diptyque/Philosykos-Eau-de-Parfum-3865.html'),
    ('Geranium Pour Monsieur', 'https://www.fragrantica.com/perfume/Frederic-Malle/Geranium-Pour-Monsieur-5911.html'),
    ("J'adore", 'https://www.fragrantica.com/perfume/Dior/J-adore-210.html'),
    ('Philosykos', 'https://www.fragrantica.com/perfume/Diptyque/Philosykos-Eau-de-Parfum-3865.html'),
    ('Colonia Essenza', 'https://www.fragrantica.com/perfume/Acqua-di-Parma/Colonia-Essenza-Special-Edition-2015-31663.html'),
    ('Fleur Narcotique', 'https://www.fragrantica.com/perfume/Ex-Nihilo/Fleur-Narcotique-27571.html'),
    ('No. 5', 'https://www.fragrantica.com/perfume/Victorio-Lucchino/No-5-Jazmim-Exotico-40568.html'),
    ('Le Jardin de Monsieur Li', 'https://www.fragrantica.com/perfume/Hermes/Le-Jardin-de-Monsieur-Li-29818.html'),
    ('Miss Dior Blooming Bouquet', 'https://www.fragrantica.com/perfume/Dior/Miss-Dior-Blooming-Bouquet-23280.html'),
    ('Magnolia Nobile', 'https://www.fragrantica.com/perfume/Acqua-di-Parma/Magnolia-Nobile-Special-Edition-2016-35351.html'),
    ('Magnolia Nobile', 'https://www.fragrantica.com/perfume/Acqua-di-Parma/Magnolia-Nobile-Special-Edition-2016-35351.html'),
    ('Tam Dao', 'https://www.fragrantica.com/perfume/Diptyque/Tam-Dao-Eau-de-Parfum-49104.html'),
    ('Wood Sage & Sea Salt', 'https://www.fragrantica.com/perfume/Jo-Malone-London/Wood-Sage-Sea-Salt-25529.html'),
    ("Terre d'Hermes Eau Gibre", 'https://www.fragrantica.com/perfume/Hermes/Terre-d-Hermes-Eau-Givree-72439.html'),
    ("L'Eau Papier", 'https://www.fragrantica.com/perfume/Diptyque/L-Eau-Papier-78658.html'),
    ('The Matcha 26', 'https://www.fragrantica.com/perfume/Le-Labo/The-Matcha-26-69731.html'),
    ("Rose of No Man's Land", 'https://www.fragrantica.com/perfume/Byredo/Rose-Of-No-Man-s-Land-31931.html'),
    ('Straight to Heaven', 'https://www.fragrantica.com/perfume/By-Kilian/Straight-to-Heaven-4323.html'),
    ('Grey Vetiver', 'https://www.fragrantica.com/perfume/Tom-Ford/Grey-Vetiver-6697.html'),
    ('Eau de Magnolia', 'https://www.fragrantica.com/perfume/Frederic-Malle/Eau-De-Magnolia-25042.html'),
    ('Eau de Mineral', 'https://www.fragrantica.com/perfume/Tom-Ford/Oud-Minerale-2023-88818.html'),
    ('Acne Studios by Frederic Malle', 'https://www.fragrantica.com/perfume/Frederic-Malle/Acne-Studios-91209.html'),
    ('Arancia di Capri', 'https://www.fragrantica.com/perfume/Acqua-di-Parma/Arancia-di-Capri-La-Riserva-107109.html'),
    ('Osmanthus', 'https://www.fragrantica.com/perfume/Molinard/Osmanthus-Eau-de-Parfum-64814.html'),
    ('Tam Dao', 'https://www.fragrantica.com/perfume/Diptyque/Tam-Dao-Eau-de-Parfum-49104.html'),
    ('Sailing Day', 'https://www.fragrantica.com/perfume/Maison-Martin-Margiela/Sailing-Day-47891.html'),
    ('Soleil Blanc', 'https://www.fragrantica.com/perfume/Tom-Ford/Soleil-Blanc-34893.html'),
    ('Bleu de Chanel', 'https://www.fragrantica.com/perfume/Chanel/Bleu-de-Chanel-Eau-de-Parfum-25967.html'),
    ('Bay 19', 'https://www.fragrantica.com/perfume/Euphorium-Brooklyn/Bay-Rum-85345.html'),
    ('Love in White', 'https://www.fragrantica.com/perfume/Creed/Love-in-White-4262.html'),
    ('Eben Fume', 'https://www.fragrantica.com/perfume/Tom-Ford/Ebene-Fume-69008.html'),
    ('Millesium Imperial', 'https://www.fragrantica.com/perfume/Creed/Millesime-Imperial-466.html'),
    ('Kaminar', 'https://www.fragrantica.com/perfume/Kate-Spade/TRULYdazzling-47551.html'),
    ('34th Avenue Saint-Germain', 'https://www.fragrantica.com/perfume/Kelly-Jones/No-3-Notes-of-Cabernet-35907.html'),
    ('Lys 41', 'https://www.fragrantica.com/perfume/Le-Labo/Lys-41-18382.html'),
    ('Noir de Noir', 'https://www.fragrantica.com/perfume/Tom-Ford/Noir-de-Noir-1822.html'),
    ('Libre', 'https://www.fragrantica.com/perfume/Yves-Saint-Laurent/Libre-56077.html'),
    ('Pear Ink', 'https://www.fragrantica.com/perfume/Loewe/Earth-Elixir-95394.html'),
    ("Lombre Dans L'eau", 'https://www.fragrantica.com/perfume/Diptyque/L-Ombre-Dans-L-Eau-Eau-de-Toilette-3962.html'),
    ('Virgin Island Water', 'https://www.fragrantica.com/perfume/Creed/Virgin-Island-Water-2007-899.html'),
    ('Apple Brandy on the Rocks', 'https://www.fragrantica.com/perfume/By-Kilian/Apple-Brandy-on-the-Rocks-68326.html'),
    ('Roasted Cherry', 'https://www.fragrantica.com/perfume/Tom-Ford/Lost-Cherry-51411.html'),
    ('Lombre de Mervais', 'https://www.fragrantica.com/perfume/The-Unleashed-Apothecary/Bois-d-Agar-Tres-Tres-Noir-72409.html'),
    ('Colonia Club', 'https://www.fragrantica.com/perfume/Acqua-di-Parma/Colonia-Club-31424.html'),
    ('Santal 33', 'https://www.fragrantica.com/perfume/Le-Labo/Santal-33-12201.html'),
    ('Melograno', 'https://www.fragrantica.com/perfume/Santa-Maria-Novella/Melograno-Pomegranate-11480.html'),
    ('French Lover', 'https://www.fragrantica.com/perfume/Frederic-Malle/French-Lover-1022.html'),
    ('Wood Satin Mood', 'https://www.fragrantica.com/perfume/Fragrance-World/Barakkat-Satin-Oud-107711.html'),
    ('Coco Mademoiselle', 'https://www.fragrantica.com/perfume/Chanel/Coco-Mademoiselle-611.html'),
    ('Marrakech', 'https://www.fragrantica.com/perfume/Aesop/Marrakech-9547.html'),
    ('Soleil Neige', 'https://www.fragrantica.com/perfume/Tom-Ford/Soleil-Neige-56737.html'),
    ("L'House Dive", 'https://www.fragrantica.com/perfume/House-of-Noya/Ocean-s-Luminescence-107534.html'),
    ('Good Girl Gone Bad Travel Set', 'https://www.fragrantica.com/perfume/By-Kilian/Voulez-Vous-Coucher-Avec-Moi-31625.html'),
    ('Dawson', 'https://www.fragrantica.com/perfume/Hotel-Dawson/Roll-The-Dice-94829.html'),
    ('Tobacco Vanille', 'https://www.fragrantica.com/perfume/Tom-Ford/Tobacco-Vanille-1825.html'),
    ('En Passin', 'https://www.fragrantica.com/perfume/Frederic-Malle/En-Passant-2793.html'),
    ('Baccarat Rouge 540', 'https://www.fragrantica.com/perfume/Maison-Francis-Kurkdjian/Baccarat-Rouge-540-33519.html'),
    ('Torino 21', 'https://www.fragrantica.com/perfume/Xerjoff/Torino21-70424.html'),
    ('Karst', 'https://www.fragrantica.com/perfume/Aesop/Karst-69187.html'),
    ('Rosa Gardenia', 'https://www.fragrantica.com/perfume/Santa-Maria-Novella/Rosa-Gardenia-70267.html'),
    ('English Pear and Freesia', 'https://www.fragrantica.com/perfume/Jo-Malone-London/English-Pear-Freesia-10314.html'),
    ('When the Rain Stops', 'https://www.fragrantica.com/perfume/Maison-Martin-Margiela/When-the-Rain-Stops-70985.html'),
    ('Delina', 'https://www.fragrantica.com/perfume/Parfums-de-Marly/Delina-43871.html'),
    ('You or Someone Like You', 'https://www.fragrantica.com/perfume/Etat-Libre-d-Orange/You-Or-Someone-Like-You-43531.html'),
    ('Super Cedar', 'https://www.fragrantica.com/perfume/Byredo/Super-Cedar-35530.html'),
    ('Miami Shake', 'https://www.fragrantica.com/perfume/Juliette-Has-A-Gun/Miami-Shake-103460.html'),
    ('Boulay Bouchoucher Abeque Moas', 'https://www.fragrantica.com/perfume/DefineMe/Nearly-Noon-100084.html'),
    ('Exit the King', 'https://www.fragrantica.com/perfume/Etat-Libre-d-Orange/Exit-The-King-62701.html'),
    ('Velvet Orchid', 'https://www.fragrantica.com/perfume/Tom-Ford/Velvet-Orchid-22963.html'),
    ('Rose', 'https://www.fragrantica.com/perfume/Mancera/Roses-Vanille-15210.html'),
    ("Terre d'Hermes", 'https://www.fragrantica.com/perfume/Hermes/Terre-d-Hermes-17.html'),
    ("Twilly d'Hermes Eau Ginger", 'https://www.fragrantica.com/perfume/Hermes/Twilly-d-Hermes-Eau-Ginger-67667.html'),
    ('Blackberry and Bay', 'https://www.fragrantica.com/perfume/Jo-Malone-London/Basil-Neroli-40419.html'),
    ('Lime Basil & Mandarin', 'https://www.fragrantica.com/perfume/Jo-Malone-London/Lime-Basil-Mandarin-5585.html'),
    ('Rolling in Love', 'https://www.fragrantica.com/perfume/By-Kilian/Rolling-in-Love-56402.html'),
    ('Green Irish Tweed', 'https://www.fragrantica.com/perfume/Creed/Green-Irish-Tweed-474.html'),
    ('Miss Dior', 'https://www.fragrantica.com/perfume/Dior/Miss-Dior-Eau-de-Parfum-2021-68905.html'),
    ('Smoking Hot', 'https://www.fragrantica.com/perfume/By-Kilian/Smoking-Hot-84413.html'),
    ('Blackberry & Bay', 'https://www.fragrantica.com/perfume/Jo-Malone-London/Blackberry-Bay-15134.html'),
    ('Gentle Fluidity Silver', 'https://www.fragrantica.com/perfume/Maison-Francis-Kurkdjian/Gentle-Fluidity-Silver-53400.html'),
    ('Neroli Amara', 'https://www.fragrantica.com/perfume/Van-Cleef-Arpels/Neroli-Amara-49913.html'),
    ('Bleu de Chanel Perfume', 'https://www.fragrantica.com/perfume/Harajuku-Lovers/Harajuku-Lovers-Sunshine-Cuties-Lil-s-Angel-7414.html'),
    ('Dark Amber & Ginger Lily Cologne Intense', 'https://www.fragrantica.com/perfume/Jo-Malone-London/Dark-Amber-Ginger-Lily-3783.html'),
    ('Tuscan Leather', 'https://www.fragrantica.com/perfume/Tom-Ford/Tuscan-Leather-1849.html'),
    ('H.B.', 'https://www.fragrantica.com/perfume/biehl-parfumkunstwerke/hb01-6131.html'),
    ("No. 5 L'eau", 'https://www.fragrantica.com/perfume/Chanel/Chanel-No-5-L-Eau-38543.html'),
    ('Vodka on the Rocks', 'https://www.fragrantica.com/perfume/By-Kilian/Vodka-on-the-Rocks-23899.html'),
    ('Inflorescence', 'https://www.fragrantica.com/perfume/Byredo/Inflorescence-17798.html'),
    ("Terre d'Hermes", 'https://www.fragrantica.com/perfume/Hermes/Terre-d-Hermes-17.html'),
    ('Eau de', 'https://www.fragrantica.com/perfume/Lacoste-Fragrances/Eau-de-Lacoste-L-12-12-White-11043.html'),
    ('Young Rose', 'https://www.fragrantica.com/perfume/Byredo/Young-Rose-69009.html'),
    ('Gabrielle Chanel Essence', 'https://www.fragrantica.com/perfume/Chanel/Gabrielle-Essence-56076.html'),
    ('Tempeau', None),
    ('Desert Dawn', 'https://www.fragrantica.com/perfume/Byredo/Desert-Dawn-96188.html'),
    ('Eau de Rhubarb Ecalate', 'https://www.fragrantica.com/perfume/Hermes/Eau-de-Rhubarbe-Ecarlate-35375.html'),
    ('Baccarat Rouge 540 Extrait de Parfum', 'https://www.fragrantica.com/perfume/Maison-Francis-Kurkdjian/Baccarat-Rouge-540-Extrait-de-Parfum-46066.html'),
    ('Chance Eau Tendre', 'https://www.fragrantica.com/perfume/Chanel/Chance-Eau-Tendre-8069.html'),
    ('Elladaria', 'https://www.fragrantica.com/perfume/Creed/Eladaria-103066.html'),
    ('Orphéon Limited Edition', 'https://www.fragrantica.com/perfume/Diptyque/Orpheon-Eau-de-Parfum-65738.html'),
    ('Cologne Shield Orb Protection', 'https://www.fragrantica.com/perfume/By-Kilian/Kologne-Shield-of-protection-73317.html'),
    ('Imperial Tea', 'https://www.fragrantica.com/perfume/By-Kilian/Imperial-Tea-2024-94042.html'),
    ('Eladaria', 'https://www.fragrantica.com/perfume/Creed/Eladaria-103066.html'),
    ('Love in Black', 'https://www.fragrantica.com/perfume/Creed/Love-in-Black-4261.html'),
    ('Sacred Wood', 'https://www.fragrantica.com/perfume/By-Kilian/Sacred-Wood-23897.html'),
    ('Moscow Mule', 'https://www.fragrantica.com/perfume/Juliette-Has-A-Gun/Moscow-Mule-47872.html'),
    ('Musk Wood', 'https://www.fragrantica.com/perfume/Avon/Musk-Wood-18372.html'),
    ('Musk Invisible', 'https://www.fragrantica.com/perfume/Eila/Invisible-Musk-78302.html'),
    ('Noir Extreme', 'https://www.fragrantica.com/perfume/Tom-Ford/Noir-Extreme-29675.html'),
    ('Night Veils Casablanca Lily Extreme', 'https://www.fragrantica.com/perfume/Byredo/Casablanca-Lily-2019-58570.html'),
    ('Rose Prick', 'https://www.fragrantica.com/perfume/Tom-Ford/Rose-Prick-58781.html'),
    ('Eau Capitale', 'https://www.fragrantica.com/perfume/Diptyque/Eau-Capitale-Eau-de-Parfum-58391.html'),
    ('H24', 'https://www.fragrantica.com/perfume/Hermes/H24-65147.html'),
    ('Oud Immortel', 'https://www.fragrantica.com/perfume/Byredo/Oud-Immortel-10759.html'),
    ('Ami Aire', 'https://www.fragrantica.com/perfume/Viorica-Cosmetics/Elixir-Floral-Lacramioara-Alba-82755.html'),
    ('Oud Satin Mood', 'https://www.fragrantica.com/perfume/Maison-Francis-Kurkdjian/Oud-Satin-Mood-30352.html'),
    ('Old Fashioned', 'https://www.fragrantica.com/perfume/By-Kilian/Old-Fashioned-96096.html'),
    ('Naxos', 'https://www.fragrantica.com/perfume/Thera-Cosmeticos/Naxos-56649.html'),
    ('Eau de Mervaille', 'https://www.fragrantica.com/perfume/Hermes/Parfum-des-Merveilles-10.html'),
    ('Inle', 'https://www.fragrantica.com/perfume/Memo-Paris/Inle-2786.html'),
    ('Bergamotto di Calabria', 'https://www.fragrantica.com/perfume/Acqua-di-Parma/Bergamotto-di-Calabria-La-Spugnatura-66175.html'),
    ('Mixed Emotions', 'https://www.fragrantica.com/perfume/Byredo/Mixed-Emotions-65525.html'),
    ('Guilty Pour Femme', 'https://www.fragrantica.com/perfume/Gucci/Guilty-Elixir-de-Parfum-pour-Homme-84547.html'),
    ('Aqua Allegoria Forte Mandarin Basilic', 'https://www.fragrantica.com/perfume/Guerlain/Aqua-Allegoria-Forte-Mandarine-Basilic-76316.html'),
    ('Playing with the Devil', 'https://www.fragrantica.com/perfume/By-Kilian/Playing-With-The-Devil-18931.html'),
    ('Man Rain Essence', 'https://www.fragrantica.com/perfume/Bvlgari/Bvlgari-Man-Rain-Essence-79335.html'),
    ("Mandarino d'Amalfi", 'https://www.fragrantica.com/perfume/Tom-Ford/Rose-D-Amalfi-71538.html'),
    ('From the Garden', 'https://www.fragrantica.com/perfume/Maison-Martin-Margiela/From-the-Garden-87457.html'),
    ('Amber Vanilla', 'https://www.fragrantica.com/perfume/The-7-Virtues/Amber-Vanilla-90294.html'),
    ('Vetiberio', 'https://www.fragrantica.com/perfume/Diptyque/Vetyverio-Eau-de-Toilette-8787.html'),
    ('Bubble Bath', 'https://www.fragrantica.com/perfume/Maison-Martin-Margiela/Bubble-Bath-60105.html'),
    ('Chance Eau Fresh', 'https://www.fragrantica.com/perfume/Chanel/Chance-Eau-Fraiche-Eau-de-Parfum-83980.html'),
    ('Uncut Gem', 'https://www.fragrantica.com/perfume/Frederic-Malle/Uncut-Gem-74926.html'),
    ('Angel di Firenze', 'https://www.fragrantica.com/perfume/Santa-Maria-Novella/Angeli-di-Firenze-73661.html'),
    ('Oolong Tea Extra de Parfum', 'https://www.fragrantica.com/perfume/Akro/Infuse-91689.html'),
    ('Orphéon Solid Perfume', 'https://www.fragrantica.com/perfume/Diptyque/Orpheon-Solid-Perfume-106892.html'),
    ('Mont Paris', 'https://www.fragrantica.com/perfume/Masque-Milano/Madeleine-64218.html'),
    ('Aqua Universale Forte', 'https://www.fragrantica.com/perfume/Maison-Francis-Kurkdjian/Aqua-Universalis-Forte-12710.html'),
    ('Erolpa', 'https://www.fragrantica.com/perfume/Creed/Erolfa-4248.html'),
    ('Back to Black', 'https://www.fragrantica.com/perfume/By-Kilian/Back-to-Black-6457.html'),
    ("Can't Stop Loving You", 'https://www.fragrantica.com/perfume/By-Kilian/Can-t-Stop-Loving-You-78735.html'),
    ('MYSLF', 'https://www.fragrantica.com/perfume/Yves-Saint-Laurent/MYSLF-Eau-de-Parfum-84094.html'),
    ('Woman in Gold', 'https://www.fragrantica.com/perfume/By-Kilian/Woman-in-Gold-46469.html'),
    ('Sauvage', 'https://www.fragrantica.com/perfume/Dior/Sauvage-31861.html'),
    ('Nuit de Cellophane', 'https://www.fragrantica.com/perfume/Serge-Lutens/Nuit-de-Cellophane-5748.html'),
    ('Rose Tonnerre', 'https://www.fragrantica.com/perfume/Frederic-Malle/Rose-Tonnerre-2851.html'),
    ('Den Thé Bréaud', 'https://www.fragrantica.com/perfume/Tableau-de-Parfums/Dark-Passage-14678.html'),
    ('Wild Bluebell', 'https://www.fragrantica.com/perfume/Jo-Malone-London/Wild-Bluebell-12310.html'),
    ('Cypress and Grapevine Cologne Intense', 'https://www.fragrantica.com/perfume/The-Art-Of-Shaving/Sandalwood-and-Cypress-Cologne-Intense-42173.html'),
    ('Eau de Soleil Blanc', 'https://www.fragrantica.com/perfume/Tom-Ford/Eau-de-Soleil-Blanc-48152.html'),
    ('La Leligieuse', 'https://www.fragrantica.com/perfume/Serge-Lutens/La-Religieuse-29636.html'),
    ("J'adore Parfum Do", 'https://www.fragrantica.com/perfume/Dior/J-adore-Eau-de-Parfum-Infinissime-x-India-Mahdavi-71116.html'),
    ('By the Fireplace', 'https://www.fragrantica.com/perfume/Maison-Martin-Margiela/By-the-Fireplace-31623.html'),
    ('Pour Homme', 'https://www.fragrantica.com/perfume/Bvlgari/Pour-Homme-Eau-De-Parfum-92563.html'),
    ('Dior Homme', 'https://www.fragrantica.com/perfume/Dior/Dior-Homme-Intense-2011-13016.html'),
    ("Twilly d'Hermes", 'https://www.fragrantica.com/perfume/Hermes/Twilly-d-Hermes-46145.html'),
    ('La Huide Berollin', 'https://www.fragrantica.com/perfume/A-La-Lune/Moonlight-Cypress-81282.html'),
    ('Un Jardin a Cité', 'https://www.fragrantica.com/perfume/Hermes/Un-Jardin-a-Cythere-79225.html'),
    ('Paradox Virtual Fla', 'https://www.fragrantica.com/perfume/Prada/Prada-Paradoxe-Virtual-Flower-95006.html'),
    ('Aqua Universale', 'https://www.fragrantica.com/perfume/Maison-Francis-Kurkdjian/Aqua-Universalis-6804.html'),
    ('Un Passion', 'https://www.fragrantica.com/perfume/Parfum-d-Empire/Un-Bel-Amour-D-ete-90980.html'),
    ('Coco Noir', 'https://www.fragrantica.com/perfume/Chanel/Coco-Noir-15963.html'),
    ('Oud', 'https://www.fragrantica.com/perfume/Maison-Crivelli/Oud-Maracuja-83842.html'),
    ('Moonlight in Heaven Coffret', 'https://www.fragrantica.com/perfume/By-Kilian/Moonlight-in-Heaven-35973.html'),
    ('Eau Rose', 'https://www.fragrantica.com/perfume/Diptyque/Eau-Rose-14214.html'),
    ('Flora Gorgeous Jasmine', 'https://www.fragrantica.com/perfume/Gucci/Flora-Gorgeous-Jasmine-75190.html'),
    ('Armani Code', 'https://www.fragrantica.com/perfume/Giorgio-Armani/Armani-Code-Parfum-75126.html'),
    ('Princess', 'https://www.fragrantica.com/perfume/By-Kilian/Princess-90174.html'),
    ('Myrrh & Tonka Cologne Intense', 'https://www.fragrantica.com/perfume/Jo-Malone-London/Myrrh-Tonka-Cologne-Intense-55760.html'),
    ('Bloom', 'https://www.fragrantica.com/perfume/The-Woods-Collection/Bloom-63718.html'),
    ('No. 5 Eau Premiere', 'https://www.fragrantica.com/perfume/Chanel/Chanel-No-5-Eau-Premiere-2015-31172.html'),
    ('Juniper Sling Eau de Toiletries', 'https://www.fragrantica.com/perfume/Neela-Vermeire-Creations/Pichola-29918.html'),
    ('Juniper Sling', 'https://www.fragrantica.com/perfume/Penhaligon-s/Juniper-Sling-13266.html'),
    ("Terre d'Hermes Parfum", 'https://www.fragrantica.com/perfume/Hermes/Terre-d-Hermes-Parfum-8282.html'),
    ('Peony & Blush Suede', 'https://www.fragrantica.com/perfume/Jo-Malone-London/Peony-Blush-Suede-18767.html'),
    ('Torino 22', 'https://www.fragrantica.com/perfume/Xerjoff/Torino22-77059.html'),
    ('Oud Extrae de Parfum', 'https://www.fragrantica.com/perfume/Extra-Virgo/Spirito-Santo-103625.html'),
    ('Rosa Nobile', 'https://www.fragrantica.com/perfume/Acqua-di-Parma/Rosa-Nobile-26577.html'),
    ('Oud Wood', 'https://www.fragrantica.com/perfume/Tom-Ford/Oud-Wood-1826.html'),
    ('Moonlight Patchouli', 'https://www.fragrantica.com/perfume/Van-Cleef-Arpels/Moonlight-Patchouli-38374.html'),
    ('Springtime in a Park', 'https://www.fragrantica.com/perfume/Maison-Martin-Margiela/Springtime-in-a-Park-55927.html'),
    ('Blue Moon Ginger Dash', 'https://www.fragrantica.com/perfume/By-Kilian/Blue-Moon-Ginger-Dash-79731.html'),
    ('Coffee Break', 'https://www.fragrantica.com/perfume/Maison-Martin-Margiela/Coffee-Break-55926.html'),
    ('Mouschio Oro', 'https://www.fragrantica.com/perfume/Santa-Maria-Novella/Muschio-Oro-12999.html'),
    ('Gris Charnel', 'https://www.fragrantica.com/perfume/BDK-Parfums/Gris-Charnel-57038.html'),
    ('Oud Silk Mood', 'https://www.fragrantica.com/perfume/Maison-Francis-Kurkdjian/Oud-Silk-Mood-48456.html'),
    ('Gentle Fluidity Gold', 'https://www.fragrantica.com/perfume/Maison-Francis-Kurkdjian/Gentle-Fluidity-Gold-53401.html'),
    ('Rose 31 (Bulk)', 'https://www.fragrantica.com/perfume/Le-Labo/Rose-31-3678.html'),
    ('Vanilla Sex', 'https://www.fragrantica.com/perfume/Tom-Ford/Vanilla-Sex-88588.html'),
    ('Vanilla Sex', 'https://www.fragrantica.com/perfume/Tom-Ford/Vanilla-Sex-88588.html'),
    ('Intoxicated', 'https://www.fragrantica.com/perfume/By-Kilian/Intoxicated-25991.html'),
    ('Rose 31', 'https://www.fragrantica.com/perfume/Le-Labo/Rose-31-3678.html'),
    ('English Oak & Hazelnut', 'https://www.fragrantica.com/perfume/Jo-Malone-London/English-Oak-Hazelnut-46187.html'),
    ('Magnolia Bliss', 'https://www.fragrantica.com/perfume/Juliette-Has-A-Gun/Magnolia-Bliss-72991.html'),
    ('Dark Lord', 'https://www.fragrantica.com/perfume/By-Kilian/Dark-Lord-50603.html'),
    ('Iris Poudre', 'https://www.fragrantica.com/perfume/Frederic-Malle/Iris-Poudre-4771.html'),
    ('Beach Walk', 'https://www.fragrantica.com/perfume/Maison-Martin-Margiela/Beach-Walk-15261.html'),
    ('Eros', 'https://www.fragrantica.com/perfume/Versace/Eros-16657.html'),
    ('Petit Martin', 'https://www.fragrantica.com/perfume/M-Micallef/Petit-Coeur-44474.html'),
    ('Rose on Ice', 'https://www.fragrantica.com/perfume/By-Kilian/Roses-on-Ice-62616.html'),
    ('Eau Duelle', 'https://www.fragrantica.com/perfume/Diptyque/Eau-Duelle-Eau-de-Toilette-9241.html'),
    ('Miss Dior Blooming Bouquet Roller Pearl', 'https://www.fragrantica.com/perfume/Dior/Miss-Dior-Blooming-Bouquet-Roller-Pearl-48407.html'),
    ('Synthetic Nature', 'https://www.fragrantica.com/perfume/Frederic-Malle/Synthetic-Nature-89055.html'),
    ('Colonia Intenza', 'https://www.fragrantica.com/perfume/Acqua-di-Parma/Colonia-Intensa-1684.html'),
    ('Himalayan', 'https://www.fragrantica.com/perfume/Obvious/Himalayan-Spell-96608.html'),
    ('Himalaya', 'https://www.fragrantica.com/perfume/Creed/Himalaya-465.html'),
    ('Un Jardin Sur Le Toi', 'https://www.fragrantica.com/perfume/Hermes/Un-Jardin-Sur-Le-Toit-11502.html'),
    ('Mon Guerlain', 'https://www.fragrantica.com/perfume/Guerlain/Mon-Guerlain-43297.html'),
    ('Black Saffron', 'https://www.fragrantica.com/perfume/Byredo/Black-Saffron-16220.html'),
    ("001 Women's", 'https://www.fragrantica.com/perfume/Manufaktura/Women-001-89672.html'),
    ('Le Jardin de Monsieur Lee', 'https://www.fragrantica.com/perfume/4160-Tuesdays/Le-Jardin-de-Monsieur-McGregor-88178.html'),
    ('Un Jardin Sur La Lagoon', 'https://www.fragrantica.com/perfume/Hermes/Un-Jardin-Sur-La-Lagune-53373.html'),
    ('Eau Sauvage', 'https://www.fragrantica.com/perfume/Dior/Eau-Sauvage-231.html'),
    ("Voyage d'Hermes", 'https://www.fragrantica.com/perfume/Hermes/Voyage-d-Hermes-7916.html'),
    ('Rose Freak', 'https://www.fragrantica.com/perfume/Bruno-Acampora/Freak-Chic-Pure-Essence-56771.html'),
    ('Libre Intense', 'https://www.fragrantica.com/perfume/Yves-Saint-Laurent/Libre-Intense-62318.html'),
    ('Bitter Peach', 'https://www.fragrantica.com/perfume/Tom-Ford/Bitter-Peach-62707.html'),
    ('Sunny Side Up', 'https://www.fragrantica.com/perfume/Juliette-Has-A-Gun/Sunny-Side-Up-46128.html'),
    ('Queen of Silk', 'https://www.fragrantica.com/perfume/Creed/Queen-of-Silk-89643.html'),
    ('Erba Pura', 'https://www.fragrantica.com/perfume/Xerjoff/Erba-Pura-55157.html'),
    ('Heaven Can Weight', 'https://www.fragrantica.com/perfume/MiN-NEW-YORK/Long-Board-25503.html'),
    ('Mon Guerlain Sparkling Bouquet', 'https://www.fragrantica.com/perfume/Guerlain/Mon-Guerlain-Sparkling-Bouquet-65546.html'),
    ('Eau de & Bergamot Cologne Intense', 'https://www.fragrantica.com/perfume/Houbigant/Cologne-Intense-33083.html'),
    ('Cherry Smoke', 'https://www.fragrantica.com/perfume/Tom-Ford/Cherry-Smoke-78578.html'),
    ('Black Orchid Perfume', 'https://www.fragrantica.com/perfume/Tom-Ford/Black-Orchid-Perfume-Lalique-Edition-42789.html'),
    ('Pieve Verte', 'https://www.fragrantica.com/perfume/Original-Penguin/Rocks-18342.html'),
    ('Promise', 'https://www.fragrantica.com/perfume/Frederic-Malle/Promise-47332.html'),
    ('Citadine Kyoto', 'https://www.fragrantica.com/perfume/10th-Avenue-Karl-Antony/Citadin-28775.html'),
    ('Café Rose', 'https://www.fragrantica.com/perfume/Tom-Ford/Cafe-Rose-2023-83771.html'),
    ('Aventus Cologne', 'https://www.fragrantica.com/perfume/Creed/Aventus-Cologne-51692.html'),
    ('Cologne Andéléville', 'https://www.fragrantica.com/perfume/Matiere-Premiere/Cologne-Cedrat-59059.html'),
    ('Eau de to Dulness', 'https://www.fragrantica.com/perfume/Juliette-Has-A-Gun/Ode-To-Dullness-84757.html'),
    ("Infusion d'Rose", 'https://www.fragrantica.com/perfume/Prada/Infusion-de-Rose-11233.html'),
    ('Scarlet Poppy Cologne Intense', 'https://www.fragrantica.com/perfume/Jo-Malone-London/Scarlet-Poppy-Cologne-Intense-79435.html'),
    ('Night Veils Tobacco Mandarin Extract de Parfum', 'https://www.fragrantica.com/perfume/Byredo/Tobacco-Mandarin-63031.html'),
    ("Terre d'Hermes Eau Intense Vetiver", 'https://www.fragrantica.com/perfume/Hermes/Terre-D-Hermes-Eau-Intense-Vetiver-50672.html'),
    ('Candy', 'https://www.fragrantica.com/perfume/Superz/Candy-87780.html'),
    ('Peony and Blush Suede', 'https://www.fragrantica.com/perfume/Oakcha/Paris-Bloom-93035.html'),
    ('Aqua di Gio Homme', 'https://www.fragrantica.com/perfume/Giorgio-Armani/Acqua-di-Gio-Blue-Edition-Pour-Homme-25615.html'),
    ('Canel Flower', 'https://www.fragrantica.com/perfume/Chanel/Gardenia-Eau-de-Parfum-41788.html'),
    ('Colonia Pura', 'https://www.fragrantica.com/perfume/Acqua-di-Parma/Acqua-di-Parma-Colonia-Pura-45876.html'),
    ('Neroli 36', 'https://www.fragrantica.com/perfume/Le-Labo/Neroli-36-6330.html'),
    ('Vanille Fatal', 'https://www.fragrantica.com/perfume/Tom-Ford/Vanille-Fatale-48029.html'),
    ('Love Extreme', 'https://www.fragrantica.com/perfume/Iggywoo/Love-Extreme-97052.html'),
    ('Magnolia Infinita', 'https://www.fragrantica.com/perfume/Acqua-di-Parma/Magnolia-Infinita-75188.html'),
    ('Le Homme', 'https://www.fragrantica.com/perfume/Milestone-Perfumes/Grandeur-Le-Homme-110387.html'),
    ('Bigarade Concentret', 'https://www.fragrantica.com/perfume/Frederic-Malle/Bigarade-Concentree-4770.html'),
    ("Twilly d'Hermes Eau Poivre", 'https://www.fragrantica.com/perfume/Hermes/Twilly-d-Hermes-Eau-Poivree-Eau-de-Parfum-55983.html'),
    ('Potpourri', 'https://www.fragrantica.com/perfume/Santa-Maria-Novella/Potpourri-11483.html'),
    ('Bibliotique', 'https://www.fragrantica.com/perfume/Eaux-Parfums/Biblioteque-100696.html'),
    ('Un Jardin en Méditerranée Eau de Toiletries', 'https://www.fragrantica.com/perfume/Yves-Rocher/Agrumes-en-Fleurs-14834.html'),
    ('Un Jardin en Méditerranée', 'https://www.fragrantica.com/perfume/Hermes/Un-Jardin-en-Mediterranee-19.html'),
    ('Lily Fantasy', 'https://www.fragrantica.com/perfume/DSH-Perfumes/Lis-Oriental-55690.html'),
    ('Ambret 9', 'https://www.fragrantica.com/perfume/Afnan/9-PM-Rebel-99238.html'),
    ('Autumn Vibe', 'https://www.fragrantica.com/perfume/Maison-Martin-Margiela/Autumn-Vibes-67789.html'),
    ('Hypnose', 'https://www.fragrantica.com/perfume/Lancome/Hypnose-170.html'),
    ('Guilty Absolute Pour Femme', 'https://www.fragrantica.com/perfume/Gucci/Gucci-Guilty-Absolute-Pour-Femme-48090.html'),
    ('Silver Birch & Lavender', 'https://www.fragrantica.com/perfume/Jo-Malone-London/Silver-Birch-Lavender-Cologne-59427.html'),
    ('Chloé Signature Naturelle', 'https://www.fragrantica.com/perfume/Chloe/Chloe-Eau-de-Parfum-Naturelle-68777.html'),
    ('Miracle', 'https://www.fragrantica.com/perfume/Lancome/Miracle-184.html'),
    ('Gabrielle Chanel', 'https://www.fragrantica.com/perfume/Chanel/Gabrielle-Chanel-Hair-Mist-56250.html'),
    ('Her. B.', 'https://www.fragrantica.com/perfume/Jequiti/Her-Brave-74202.html'),
    ('Royal Wood', 'https://www.fragrantica.com/perfume/Rayhaan/Royal-Wood-107856.html'),
    ('Caprifolio', 'https://www.fragrantica.com/perfume/Santa-Maria-Novella/Caprifoglio-Honeysuckle-11465.html'),
    ('Libre Absolute Platin', 'https://www.fragrantica.com/perfume/Yves-Saint-Laurent/Libre-L-Absolu-Platine-83296.html'),
    ('Endymion', 'https://www.fragrantica.com/perfume/Penhaligon-s/Endymion-5674.html'),
    ('Eau de Neroli', 'https://www.fragrantica.com/perfume/Hermes/Eau-de-Neroli-Dore-35376.html'),
    ('Lorprene', None),
    ('Jasmine Sambac & Marigold Cologne Intense', 'https://www.fragrantica.com/perfume/Jo-Malone-London/Jasmine-Sambac-Marigold-49714.html'),
    ('Lady Vengeance', 'https://www.fragrantica.com/perfume/Juliette-Has-A-Gun/Lady-Vengeance-1715.html'),
    ('Popourri', 'https://www.fragrantica.com/perfume/Santa-Maria-Novella/Potpourri-11483.html'),
    ('Jafferano', 'https://www.fragrantica.com/perfume/Acqua-di-Parma/Zafferano-73365.html'),
    ('Poison Girl', 'https://www.fragrantica.com/perfume/Dior/Poison-Girl-35561.html'),
    ('Coco', 'https://www.fragrantica.com/perfume/Chanel/Coco-Mademoiselle-611.html'),
    ('Coco', 'https://www.fragrantica.com/perfume/Chanel/Coco-Mademoiselle-611.html'),
    ('Pearl Wood', 'https://www.fragrantica.com/perfume/Oriza-L-Legrand/Horizon-23717.html'),
    ('Santal Calling', 'https://www.fragrantica.com/perfume/Ex-Nihilo/Santal-Calling-75961.html'),
    ('Rose Gold', 'https://www.fragrantica.com/perfume/Bvlgari/Rose-Goldea-39834.html'),
    ('Men Eau Fresh', 'https://www.fragrantica.com/perfume/Avon/Fresh-Citrus-58673.html'),
    ('Cologne 352', 'https://www.fragrantica.com/perfume/Ex-Nihilo/Cologne-352-27569.html'),
    ('Patchouli Blanc', 'https://www.fragrantica.com/perfume/Van-Cleef-Arpels/Patchouli-Blanc-71670.html'),
    ('Eau de Mervaille Bleu', 'https://www.fragrantica.com/perfume/Hermes/Eau-des-Merveilles-Bleue-42747.html'),
    ('The Favorite', 'https://www.fragrantica.com/perfume/Tom-Ford/White-Suede-6386.html'),
    ("Rose d'Amalfi", 'https://www.fragrantica.com/perfume/Tom-Ford/Rose-D-Amalfi-71538.html'),
    ('Nectarine Blossom & Honey', 'https://www.fragrantica.com/perfume/Jo-Malone-London/Nectarine-Blossom-Honey-3782.html'),
    ('Aqua Media Cologne Forte', 'https://www.fragrantica.com/perfume/Maison-Francis-Kurkdjian/Aqua-Media-Cologne-Forte-82030.html'),
    ('Rossle', 'https://www.fragrantica.com/perfume/Prada/No14-Rossetto-17171.html'),
    ('Night Veils Cellier Extract de Parfum', 'https://www.fragrantica.com/perfume/Byredo/Sellier-58572.html'),
    ('Neroli Sauvage s', 'https://www.fragrantica.com/perfume/Creed/Neroli-Sauvage-475.html'),
    ('Neroli Sauvage', 'https://www.fragrantica.com/perfume/Creed/Neroli-Sauvage-475.html'),
    ('Sandalo', 'https://www.fragrantica.com/perfume/Acqua-di-Parma/Sandalo-Eau-de-Parfum-56002.html'),
    ('Lavande 31', 'https://www.fragrantica.com/perfume/Le-Labo/Lavande-31-84249.html'),
    ('Guilty Elixir de Parfum Pour Femme', 'https://www.fragrantica.com/perfume/Gucci/Gucci-Guilty-Elixir-de-Parfum-pour-Femme-84546.html'),
    ('Spring Flower', 'https://www.fragrantica.com/perfume/Creed/Spring-Flower-471.html'),
    ('Apolonia Perfume', 'https://www.fragrantica.com/perfume/Giardini-Di-Toscana/Colonia-Nobile-77063.html'),
    ('Outrageous', 'https://www.fragrantica.com/perfume/Frederic-Malle/Outrageous-2720.html'),
    ('Un Jardin Sur Toi', 'https://www.fragrantica.com/perfume/Hermes/Un-Jardin-Sur-Le-Toit-11502.html'),
    ('Wood Sage & Sea Salt Gift Package', 'https://www.fragrantica.com/perfume/Tiziana-Terenzi/Tyrenum-74548.html'),
    ('Noir Extreme Perfume', 'https://www.fragrantica.com/perfume/Lacoste-Fragrances/Match-Point-Eau-De-Parfum-71660.html'),
    ('English Pear & Freesia', 'https://www.fragrantica.com/perfume/Jo-Malone-London/English-Pear-Freesia-10314.html'),
    ('Miss Dior', 'https://www.fragrantica.com/perfume/Dior/Miss-Dior-Eau-de-Parfum-2021-68905.html'),
    ('French Leather', 'https://www.fragrantica.com/perfume/Memo-Paris/French-Leather-28049.html'),
    ('Geranium Odorata', 'https://www.fragrantica.com/perfume/Diptyque/Geranium-Odorata-24919.html'),
    ('Eau Duelle', 'https://www.fragrantica.com/perfume/Diptyque/Eau-Duelle-Eau-de-Toilette-9241.html'),
    ('Torino 24', 'https://www.fragrantica.com/perfume/Xerjoff/Torino24-99380.html'),
    ('Miss Dior Perfume', 'https://www.fragrantica.com/perfume/Dior/Miss-Dior-Eau-de-Parfum-2021-68905.html'),
    ('Iris', 'https://www.fragrantica.com/perfume/Maison-Crivelli/Iris-Malikhan-62617.html'),
    ("Tutti Twilly d'Hermes", 'https://www.fragrantica.com/perfume/Hermes/Tutti-Twilly-d-Hermes-83963.html'),
    ('Yuzu', 'https://www.fragrantica.com/perfume/Spiritica/Yuzuyakuza-102995.html'),
    ('Juliet', 'https://www.fragrantica.com/perfume/Scents-of-Verona-by-SIGILLO-VERONA/Juliet-101273.html'),
    ('Love in White Summer', 'https://www.fragrantica.com/perfume/Creed/Love-in-White-for-Summer-49805.html'),
    ('Eau Capitale Solid Perfume', 'https://www.fragrantica.com/perfume/Diptyque/Eau-Capitale-Solid-Perfume-106895.html'),
    ('Soul of the Forest', 'https://www.fragrantica.com/perfume/Maison-Martin-Margiela/Soul-Of-The-Forest-41185.html'),
    ('Grey Vetiver Perfume', 'https://www.fragrantica.com/perfume/The-House-of-Oud/Each-Other-51918.html'),
    ('Lipstick Rose', 'https://www.fragrantica.com/perfume/Frederic-Malle/Lipstick-Rose-2799.html'),
    ('Glome', 'https://www.fragrantica.com/perfume/Rochas/Globe-2152.html'),
    ('Moonlight in Heaven Refill', 'https://www.fragrantica.com/perfume/By-Kilian/Moonlight-in-Heaven-35973.html'),
    ('Chance', 'https://www.fragrantica.com/perfume/Chanel/Chance-Eau-Tendre-8069.html'),
    ('Mon Paris Lumière Eau de Toiletries', 'https://www.fragrantica.com/perfume/Yves-Saint-Laurent/Mon-Paris-Lumiere-72606.html'),
    ('Night Veils Vanille Antique Extract de Parfum', 'https://www.fragrantica.com/perfume/Byredo/Vanille-Antique-73438.html'),
    ('Mandarino di Sicilia', 'https://www.fragrantica.com/perfume/Acqua-di-Parma/Mandarino-di-Sicilia-92455.html'),
    ('Aqua Universal Forte', 'https://www.fragrantica.com/perfume/Maison-Francis-Kurkdjian/Aqua-Universalis-Forte-12710.html'),
    ('Eleventh Hour', 'https://www.fragrantica.com/perfume/Byredo/Eleventh-Hour-50934.html'),
    ('Cherry Blossom', 'https://www.fragrantica.com/perfume/Floris/Cherry-Blossom-17535.html'),
    ('African Leather', 'https://www.fragrantica.com/perfume/Memo-Paris/African-Leather-31383.html'),
    ('Ghost in the Shell', 'https://www.fragrantica.com/perfume/Etat-Libre-d-Orange/The-Ghost-In-The-Shell-69412.html'),
    ('Velvet Haze', 'https://www.fragrantica.com/perfume/Byredo/Velvet-Haze-46358.html'),
    ('Pretnotique Poison', None),
    ('Libre', 'https://www.fragrantica.com/perfume/Yves-Saint-Laurent/Libre-56077.html'),
    ('Miracetti', 'https://www.fragrantica.com/perfume/Aesop/Miraceti-69186.html'),
    ('Chance', 'https://www.fragrantica.com/perfume/Chanel/Chance-Eau-Tendre-8069.html'),
    ('Myr Mistère', 'https://www.fragrantica.com/perfume/Jequiti/Segredos-do-Mar-Misterio-das-Ondas-81290.html'),
    ('Apom', 'https://www.fragrantica.com/perfume/Maison-Francis-Kurkdjian/APOM-95969.html'),
    ('Rose & Cuir', 'https://www.fragrantica.com/perfume/Frederic-Malle/Rose-Cuir-56516.html'),
    ('Bright Crystal Absolute', 'https://www.fragrantica.com/perfume/Maher-Olfactive/Crystal-Moon-60608.html'),
    ('Magnolia (Medici Garden Collection)', 'https://www.fragrantica.com/perfume/Santa-Maria-Novella/Magnolia-2023-83042.html'),
    ('Hermann', 'https://www.fragrantica.com/perfume/Etat-Libre-d-Orange/Hermann-a-mes-Cotes-me-Paraissait-une-Ombre-34730.html'),
    ('Experimentum Crucis', 'https://www.fragrantica.com/perfume/Etat-Libre-d-Orange/Experimentum-Crucis-54453.html'),
    ('Afternoon Delight', 'https://www.fragrantica.com/perfume/Maison-Martin-Margiela/Afternoon-Delight-95923.html'),
    ('Ylang 49 (Bulk)', 'https://www.fragrantica.com/perfume/Le-Labo/Ylang-49-18383.html'),
    ('Uranon', 'https://www.fragrantica.com/perfume/Manuel-Attardi/Urano-99743.html'),
    ('Tiffany & Love for Him', 'https://www.fragrantica.com/perfume/Tiffany/Tiffany-Love-For-Him-57031.html'),
    ('Gelsomino (Medici Garden Collection)', 'https://www.fragrantica.com/perfume/12-Parfumeurs-Francais/Tuileries-42910.html'),
    ("Infusion d'Iris", 'https://www.fragrantica.com/perfume/Prada/Infusion-d-Iris-1795.html'),
    ('Jasmin 17', 'https://www.fragrantica.com/perfume/Le-Labo/Jasmin-17-6337.html'),
    ('Pure Poison', 'https://www.fragrantica.com/perfume/Dior/Pure-Poison-214.html'),
    ('Tuberose Angelica Cologne Intense', 'https://www.fragrantica.com/perfume/Jo-Malone-London/Tuberose-Angelica-Limited-Edition-26787.html'),
    ('I Am Trash', 'https://www.fragrantica.com/perfume/Etat-Libre-d-Orange/I-am-Trash-Les-Fleurs-du-Dechet-50009.html'),
    ('Love Eau Fresh', 'https://www.fragrantica.com/perfume/Marc-Jacobs/Daisy-Love-Eau-So-Sweet-Petals-60025.html'),
    ("L'Oe de Hesperides", 'https://www.fragrantica.com/perfume/Prudence-Paris/No-9-11954.html'),
    ('Eau de Citron Noir', 'https://www.fragrantica.com/perfume/Hermes/Eau-de-Citron-Noir-49231.html'),
    ('Mandoro di Sicilia', 'https://www.fragrantica.com/perfume/Boellis/Fiore-di-Mandorlo-di-Sicilia-56653.html'),
    ('34th Avenue Saint-Germain', 'https://www.fragrantica.com/perfume/Kelly-Jones/No-3-Notes-of-Cabernet-35907.html'),
    ('Homme à la Rose', 'https://www.fragrantica.com/perfume/Maison-Francis-Kurkdjian/L-Homme-A-la-Rose-61779.html'),
    ('English Pear and Sweet Pea', 'https://www.fragrantica.com/perfume/Kate-Moss/Lilabelle-Truly-Adorable-15378.html'),
    ('Original Santal', 'https://www.fragrantica.com/perfume/Creed/Original-Santal-473.html'),
    ("Miss Dior Rose N' Roses", 'https://www.fragrantica.com/perfume/Dior/Miss-Dior-Rose-N-Roses-58562.html'),
    ('My Way', 'https://www.fragrantica.com/perfume/Giorgio-Armani/My-Way-62036.html'),
    ('Tiffany', 'https://www.fragrantica.com/perfume/Tiffany/Tiffany-Co-46039.html'),
    ('Beau de Jour', 'https://www.fragrantica.com/perfume/Tom-Ford/Beau-De-Jour-Eau-de-Parfum-59064.html'),
    ('Verbena', 'https://www.fragrantica.com/perfume/Granado/Verbena-42452.html'),
    ('Luna Rossa Carbon', 'https://www.fragrantica.com/perfume/Prada/Luna-Rossa-Carbon-43402.html'),
    ('On a Date', 'https://www.fragrantica.com/perfume/Maison-Martin-Margiela/On-A-Date-78292.html'),
    ('Tabacco Toscano', 'https://www.fragrantica.com/perfume/Santa-Maria-Novella/Tabacco-Toscano-16067.html'),
    ('Wood', 'https://www.fragrantica.com/perfume/d-grayi/Wood-90631.html'),
    ('Noir', 'https://www.fragrantica.com/perfume/Tom-Ford/Noir-Extreme-29675.html'),
    ('Rose Tonnerre', 'https://www.fragrantica.com/perfume/Frederic-Malle/Rose-Tonnerre-2851.html'),
    ("L'Oise La Rose", 'https://www.fragrantica.com/perfume/Lancome/Absolue-1001-Roses-94910.html'),
    ('Eau Rose Solid Parfum', 'https://www.fragrantica.com/perfume/Velvet-Sweet-Pea-s-Purrfumery/Rose-Jasmine-32447.html'),
    ('Night Veils Ren de Nuit Extract de Parfum', 'https://www.fragrantica.com/perfume/Lancome/La-Nuit-Tresor-Le-Parfum-89120.html'),
    ("L'Ode Hesfrides", 'https://www.fragrantica.com/perfume/Olfactum/Hesperides-73716.html'),
    ('Portrait the Tragedy Lord George', 'https://www.fragrantica.com/perfume/Penhaligon-s/The-Tragedy-of-Lord-George-40716.html'),
    ('Animalique', 'https://www.fragrantica.com/perfume/Byredo/Animalique-85157.html'),
    ('Guilty Elixir de Parfum Pour Homme', 'https://www.fragrantica.com/perfume/Gucci/Guilty-Elixir-de-Parfum-pour-Homme-84547.html'),
    ('For Her', 'https://www.fragrantica.com/perfume/Mandarina-Duck/For-Her-73609.html'),
    ('English Pear and Freesia Special Edition', 'https://www.fragrantica.com/perfume/Jo-Malone-London/Tuberose-Angelica-Limited-Edition-26787.html'),
    ('Dior Addict Eau Fraîche', 'https://www.fragrantica.com/perfume/Dior/Dior-Addict-Eau-Fraiche-2014-25611.html'),
    ('Music for a Day', 'https://www.fragrantica.com/perfume/Nobile-1942/I-Zucchero-Candito-34481.html'),
    ('Les Méditerranées', 'https://www.fragrantica.com/perfume/Lancome/O-Zenith-106346.html'),
    ('Black Opium Over Red', 'https://www.fragrantica.com/perfume/Yves-Saint-Laurent/Black-Opium-Over-Red-88707.html'),
    ('Eau de Mervaille Blue', 'https://www.fragrantica.com/perfume/Hermes/Eau-des-Merveilles-Bleue-42747.html'),
    ('Black Lacquer', 'https://www.fragrantica.com/perfume/Tom-Ford/Black-Lacquer-95808.html'),
    ('The Night', 'https://www.fragrantica.com/perfume/Frederic-Malle/The-Night-28407.html'),
    ('Wood Satin Mood Extrae de Parfum', 'https://www.fragrantica.com/perfume/Tiziana-Terenzi/Vele-44361.html'),
    ('La Pin du Monde', 'https://www.fragrantica.com/perfume/DI-SER/Zuko-106045.html'),
    ('Fahrenheit', 'https://www.fragrantica.com/perfume/Dior/Fahrenheit-228.html'),
    ('Viking', 'https://www.fragrantica.com/perfume/Creed/Viking-41698.html'),
    ('Monsieur', 'https://www.fragrantica.com/perfume/Frederic-Malle/Monsieur-32590.html'),
    ('Viking Cologne s', 'https://www.fragrantica.com/perfume/Creed/Viking-Cologne-67039.html'),
    ('Viking Cologne', 'https://www.fragrantica.com/perfume/Creed/Viking-Cologne-67039.html'),
    ('Allure Homme', 'https://www.fragrantica.com/perfume/Chanel/Allure-Homme-Sport-Eau-Extreme-14669.html'),
    ('Velvet Rose & Intense', 'https://www.fragrantica.com/perfume/Jo-Malone-London/Velvet-Rose-Oud-Cologne-Intense-71509.html'),
    ('Bois du Portugal', 'https://www.fragrantica.com/perfume/Creed/Bois-du-Portugal-3805.html'),
    ('Colonia', 'https://www.fragrantica.com/perfume/Antonio-Miro/Colonia-10625.html'),
    ('Colonia Il Profumo', 'https://www.fragrantica.com/perfume/Acqua-di-Parma/Colonia-Il-Profumo-100793.html'),
    ('Eau Pour Homme', 'https://www.fragrantica.com/perfume/L-T-Piver/Eau-pour-Homme-40529.html'),
    ('Orange Blossom', 'https://www.fragrantica.com/perfume/Jo-Malone-London/Orange-Blossom-2279.html'),
    ('Ex Vetiver', 'https://www.fragrantica.com/perfume/Juliette-Has-A-Gun/Ex-Vetiver-96854.html'),
    ('Woman in Gold Coffret', 'https://www.fragrantica.com/perfume/By-Kilian/Woman-in-Gold-46469.html'),
    ('Honeysuckle & Davana', 'https://www.fragrantica.com/perfume/Jo-Malone-London/Honeysuckle-Davana-51266.html'),
    ('Aqua di Gioia', 'https://www.fragrantica.com/perfume/Giorgio-Armani/Acqua-di-Gioia-8442.html'),
    ('Jasmine Rouge', 'https://www.fragrantica.com/perfume/Tom-Ford/Santal-Blush-12766.html'),
    ('Royal Princess Wood', 'https://www.fragrantica.com/perfume/Creed/Royal-Princess-Oud-2024-100586.html'),
    ('Eau de Mervais', 'https://www.fragrantica.com/perfume/Lacoste-Fragrances/Eau-de-Lacoste-L-12-12-White-11043.html'),
    ('Hope', 'https://www.fragrantica.com/perfume/Frederic-Malle/Hope-95624.html'),
    ('Nectarine Blossom & Honey Gift Package', 'https://www.fragrantica.com/perfume/St-James-Of-London/Honeycomb-Elderflower-65847.html'),
    ('Libre Le Parfum', 'https://www.fragrantica.com/perfume/Yves-Saint-Laurent/Libre-Le-Parfum-75676.html'),
    ('Dawson Solid Perfume', 'https://www.fragrantica.com/perfume/Hotel-Dawson/Roll-The-Dice-94829.html'),
    ('Soleil Neige Perfume', 'https://www.fragrantica.com/perfume/Parfumeurs-du-Monde/Terre-de-soleil-102270.html'),
    ('Black Phantom Travel Set', 'https://www.fragrantica.com/perfume/Emper/Phantom-My-Hero-103431.html'),
    ('Eau Sauvage Perfume', 'https://www.fragrantica.com/perfume/Dior/Eau-Sauvage-231.html'),
    ('Miss Dior Roller Pearl', 'https://www.fragrantica.com/perfume/Dior/Miss-Dior-Blooming-Bouquet-Roller-Pearl-48407.html'),
    ('Alchemist Garden A Floral Verse', 'https://www.fragrantica.com/perfume/Gucci/A-Floral-Verse-81511.html'),
    ('Irresistible', 'https://www.fragrantica.com/perfume/Alkemia-Perfumes/Irresistible-54095.html'),
    ('Good Girl Gone Bad Refill', 'https://www.fragrantica.com/perfume/By-Kilian/Voulez-Vous-Coucher-Avec-Moi-31625.html'),
    ('Tiffany & Love for Her', 'https://www.fragrantica.com/perfume/Tiffany/Tiffany-Love-For-Her-57032.html'),
    ('Barenia', 'https://www.fragrantica.com/perfume/Hermes/Barenia-96428.html'),
    ("J'adore Infinissime", 'https://www.fragrantica.com/perfume/Dior/J-Adore-Infinissime-62638.html'),
    ('Man Glacial Essence', 'https://www.fragrantica.com/perfume/Bvlgari/Bvlgari-Man-Glacial-Essence-62569.html'),
    ('Santalle Blush', 'https://www.fragrantica.com/perfume/Tom-Ford/Santal-Blush-12766.html'),
    ('Vetiver Morocco', 'https://www.fragrantica.com/perfume/URBIETA14/Ondarea-73194.html'),
    ("Fleur d'Orangie", 'https://www.fragrantica.com/perfume/Le-Labo/Fleur-d-Oranger-27-6331.html'),
    ('Pour Him Vetiver Musk', 'https://www.fragrantica.com/perfume/Avery/Peep-Pour-Toi-57370.html'),
    ("Concentrée d'Orangie Berthe", 'https://www.fragrantica.com/perfume/Jil-Sander/Sun-Men-Fizz-36972.html'),
    ('Black Opium', 'https://www.fragrantica.com/perfume/Yves-Saint-Laurent/Black-Opium-25324.html'),
    ('Passe Soiree', 'https://www.fragrantica.com/perfume/Serge-Lutens/Le-Participe-Passe-50234.html'),
    ('Eau Mohely', 'https://www.fragrantica.com/perfume/Diptyque/Eau-Moheli-18180.html'),
    ('Tonka 25', 'https://www.fragrantica.com/perfume/Le-Labo/Tonka-25-51697.html'),
    ('Sauvage Elixir', 'https://www.fragrantica.com/perfume/Dior/Sauvage-Elixir-68415.html'),
    ("L'Orévé Dubert", 'https://www.fragrantica.com/perfume/Jacques-Fath/L-Oree-du-Bois-44043.html'),
    ('Ambra', 'https://www.fragrantica.com/perfume/Nishane/Ambra-Calabria-30568.html'),
    ('Allure', 'https://www.fragrantica.com/perfume/Chanel/Allure-Homme-Sport-Eau-Extreme-14669.html'),
    ('Allure', 'https://www.fragrantica.com/perfume/Chanel/Allure-Homme-Sport-Eau-Extreme-14669.html'),
    ('Acqua della Regina', 'https://www.fragrantica.com/perfume/Santa-Maria-Novella/Acqua-Della-Regina-73280.html'),
    ('Red Hibiscus Cologne Intense', 'https://www.fragrantica.com/perfume/Jo-Malone-London/Red-Hibiscus-Cologne-Intense-65928.html'),
    ('Peony and Blush Suede Gift Package', 'https://www.fragrantica.com/perfume/Oakcha/Paris-Bloom-93035.html'),
    ('Tobacco Vanillin', 'https://www.fragrantica.com/perfume/Phronema-Perfumes/Audition-98099.html'),
    ('Vetiver 46 (Bulk Product)', 'https://www.fragrantica.com/perfume/Le-Labo/Vetiver-46-6328.html'),
    ('Ylang 49', 'https://www.fragrantica.com/perfume/Le-Labo/Ylang-49-18383.html'),
    ('Coco Mademoiselle Perfume', 'https://www.fragrantica.com/perfume/Chanel/Coco-Mademoiselle-L-Eau-Privee-62194.html'),
    ('Costa Azura Perfume', 'https://www.fragrantica.com/perfume/Van-Gils/His-Aura-by-Night-5622.html'),
    ('Ilha Domel', 'https://www.fragrantica.com/perfume/Memo-Paris/Ilha-do-Mel-30274.html'),
    ('Good Girl Gone Bad Eau Fresh Refill', 'https://www.fragrantica.com/perfume/By-Kilian/Good-Girl-Gone-Bad-Eau-Fraiche-59813.html'),
    ('Flora Gorgeous Magnolia', 'https://www.fragrantica.com/perfume/Gucci/Flora-Gorgeous-Magnolia-83621.html'),
    ('Siwa', 'https://www.fragrantica.com/perfume/Memo-Paris/Siwa-2784.html'),
    ('Atomic Rose s', 'https://www.fragrantica.com/perfume/Initio-Parfums-Prives/Atomic-Rose-57587.html'),
    ('Poppy & Barley', 'https://www.fragrantica.com/perfume/Jo-Malone-London/Poppy-Barley-56152.html'),
    ('Ladanum 18', 'https://www.fragrantica.com/perfume/Le-Labo/Labdanum-18-7848.html'),
    ('Sal Goss', 'https://www.fragrantica.com/perfume/Gritti/Gossip-Night-79276.html'),
    ('Bloom Intense', 'https://www.fragrantica.com/perfume/Gucci/Gucci-Bloom-Intense-79602.html'),
    ('La Nuit de Homme Parfum', 'https://www.fragrantica.com/perfume/Yves-Saint-Laurent/La-Nuit-de-L-Homme-Le-Parfum-10206.html'),
    ('Under the Stars', 'https://www.fragrantica.com/perfume/Maison-Martin-Margiela/Under-the-Stars-83774.html'),
    ('My Way Nectar', 'https://www.fragrantica.com/perfume/Giorgio-Armani/My-Way-Nectar-88938.html'),
    ('Royal Princess Oud', 'https://www.fragrantica.com/perfume/Creed/Royal-Princess-Oud-31563.html'),
    ('La Huile Tour de Pere', 'https://www.fragrantica.com/perfume/The-Unleashed-Apothecary/Bois-d-Agar-Tres-Tres-Noir-72409.html'),
    ('Eau de Campagne', 'https://www.fragrantica.com/perfume/Sisley/Eau-de-Campagne-1003.html'),
    ('Guilty Pour Homme Parfum', 'https://www.fragrantica.com/perfume/Gucci/Gucci-Guilty-Pour-Homme-Parfum-71378.html'),
    ('Paragon Extrae de Parfum', 'https://www.fragrantica.com/perfume/Paragon-Perfumes/The-Haunted-17530.html'),
    ('Tabarom', 'https://www.fragrantica.com/perfume/Antonio-Visconti/Tabarom-11228.html'),
    ('Tabarom', 'https://www.fragrantica.com/perfume/Antonio-Visconti/Tabarom-11228.html'),
    ('Diorissimo', 'https://www.fragrantica.com/perfume/Dior/Diorissimo-224.html'),
    ('Moonlight Rose', 'https://www.fragrantica.com/perfume/Van-Cleef-Arpels/Moonlight-Rose-79179.html'),
    ('Wood Silk Mood Extrait de Parfum', 'https://www.fragrantica.com/perfume/Zoologist-Perfumes/Tiger-80103.html'),
    ('English Pear and Sweet Pea Special Edition', 'https://www.fragrantica.com/perfume/Kate-Moss/Lilabelle-Truly-Adorable-15378.html'),
    ('Eau de White Floral', 'https://www.fragrantica.com/perfume/Jill-Stuart/Relax-Eau-de-White-Floral-17023.html'),
    ('De Los Santos', 'https://www.fragrantica.com/perfume/Byredo/De-Los-Santos-72693.html'),
    ('Aqua Allegoria Bosca Vanilla Forte', 'https://www.fragrantica.com/perfume/Guerlain/Aqua-Allegoria-Forte-Bosca-Vanilla-83152.html'),
    ('Vizaria (Medici Garden Collection)', None),
    ('No. 5', 'https://www.fragrantica.com/perfume/Victorio-Lucchino/No-5-Jazmim-Exotico-40568.html'),
    ('Cologne Bigarade', 'https://www.fragrantica.com/perfume/Frederic-Malle/Cologne-Bigarade-4769.html'),
    ('Vanille Fatale', 'https://www.fragrantica.com/perfume/Tom-Ford/Vanille-Fatale-48029.html'),
    ('Pomegranate Noir', 'https://www.fragrantica.com/perfume/Jo-Malone-London/Pomegranate-Noir-5581.html'),
    ('Omnia Crystalline', 'https://www.fragrantica.com/perfume/Bvlgari/Omnia-Crystalline-152.html'),
    ('Sherwood', 'https://www.fragrantica.com/perfume/Memo-Paris/Sherwood-77998.html'),
    ("L'Anterdi", 'https://www.fragrantica.com/perfume/Givenchy/L-Interdit-Eau-de-Parfum-51488.html'),
    ('Under the Lemon Tree', 'https://www.fragrantica.com/perfume/Maison-Martin-Margiela/Under-The-Lemon-Tree-53379.html'),
    ('Idol Nectar', 'https://www.fragrantica.com/perfume/Lancome/Idole-Nectar-74137.html'),
    ('Allure Sensual', 'https://www.fragrantica.com/perfume/House-of-Brandt/Bois-de-Santal-89216.html'),
    ('Nio Parfum', 'https://www.fragrantica.com/perfume/Darren-Alan-Perfumes/Chypre-No-1-Parfum-87659.html'),
    ('Dior Homme', 'https://www.fragrantica.com/perfume/Dior/Dior-Homme-Intense-2011-13016.html'),
    ('Passe Soiree Extrait', 'https://www.fragrantica.com/perfume/Serge-Lutens/Le-Participe-Passe-50234.html'),
    ('Févonius Extrait', 'https://www.fragrantica.com/perfume/Nishane/Favonius-70388.html'),
    ("L'Evé Dalma", 'https://www.fragrantica.com/perfume/Mona-di-Orio/Domaine-79234.html'),
    ('Nomade', 'https://www.fragrantica.com/perfume/Chloe/Nomade-48434.html'),
    ('Bloom', 'https://www.fragrantica.com/perfume/The-Woods-Collection/Bloom-63718.html'),
    ('Hajibat Extrait', None),
    ('Bright Crystal', 'https://www.fragrantica.com/perfume/Versace/Bright-Crystal-632.html'),
    ("L'Instante de Guerlain", 'https://www.fragrantica.com/perfume/Guerlain/L-Instant-de-Guerlain-pour-Homme-EDP-44763.html'),
    ('Le Parfum de Thérèse', 'https://www.fragrantica.com/perfume/Frederic-Malle/Le-Parfum-de-Therese-4772.html'),
    ('Legendary Samsara', 'https://www.fragrantica.com/perfume/Xerjoff/Tony-Iommi-Monkey-Special-70789.html'),
    ('Wood & Spice', 'https://www.fragrantica.com/perfume/Proraso/Wood-Spice-46025.html'),
    ("Alba d'Seoul", 'https://www.fragrantica.com/perfume/Santa-Maria-Novella/Alba-di-Seoul-17976.html'),
    ('Pleasure', 'https://www.fragrantica.com/perfume/Bouge/Pleasure-61726.html'),
    ('Pleasure', 'https://www.fragrantica.com/perfume/Bouge/Pleasure-61726.html'),
    ("Jour d'Hermes Absolu", 'https://www.fragrantica.com/perfume/Hermes/Jour-d-Hermes-Absolu-23907.html'),
    ('Good Girl Gone Bad Eau Fresh', 'https://www.fragrantica.com/perfume/By-Kilian/Good-Girl-Gone-Bad-Eau-Fraiche-59813.html'),
    ('Bamboo', 'https://www.fragrantica.com/perfume/By-Kilian/Bamboo-Harmony-14330.html'),
    ('Aqua Allegoria Rosa Rosa', 'https://www.fragrantica.com/perfume/Guerlain/Aqua-Allegoria-Rosa-Verde-102669.html'),
    ('Elle', 'https://www.fragrantica.com/perfume/Yves-Saint-Laurent/Elle-1574.html'),
    ('Poivre Noir', 'https://www.fragrantica.com/perfume/Serge-Lutens/Poivre-Noir-75836.html'),
    ('Orchid Leather', 'https://www.fragrantica.com/perfume/Van-Cleef-Arpels/Orchid-Leather-65992.html'),
    ('Green Neroli', 'https://www.fragrantica.com/perfume/Creed/Green-Neroli-63618.html'),
    ('Aqua Allegoria Porte Rosa Rosa', 'https://www.fragrantica.com/perfume/Guerlain/Aqua-Allegoria-Forte-Rosa-Rossa-76315.html'),
    ('Wynne Amourette', None),
    ('Gentleman', 'https://www.fragrantica.com/perfume/Givenchy/Gentleman-Eau-de-Parfum-Reserve-Privee-71272.html'),
    ('Eyes Closed', 'https://www.fragrantica.com/perfume/Byredo/Eyes-Closed-76339.html'),
    ('Lime Basil & Mandarin Gift Package', 'https://www.fragrantica.com/perfume/L-Occitane-Au-Bresil/Dama-da-Noite-37907.html'),
    ('La Vie Belle Intensement', 'https://www.fragrantica.com/perfume/Lancome/La-Vie-Est-Belle-Intensement-59326.html'),
    ('La Dumfute Song Quécy', 'https://www.fragrantica.com/perfume/Azman/Song-For-a-Wanderer-74500.html'),
    ('Bois Doré', 'https://www.fragrantica.com/perfume/Van-Cleef-Arpels/Bois-Dore-44864.html'),
    ('Vetiver 46', 'https://www.fragrantica.com/perfume/Le-Labo/Vetiver-46-6328.html'),
    ('Orchidee Vanille', 'https://www.fragrantica.com/perfume/Van-Cleef-Arpels/Orchidee-Vanille-6463.html'),
    ('Angelique Su La Plus', 'https://www.fragrantica.com/perfume/Guerlain/Angelique-Noire-1021.html'),
    ('Dior Addict', 'https://www.fragrantica.com/perfume/Dior/Dior-Addict-215.html'),
    ('Guilty Absolute Pour Homme', 'https://www.fragrantica.com/perfume/Gucci/Gucci-Guilty-Oud-50012.html'),
    ('Serge Noir', 'https://www.fragrantica.com/perfume/Serge-Lutens/Serge-Noire-4088.html'),
    ('Aqua Florentina', 'https://www.fragrantica.com/perfume/Xerjoff/Aqua-Regia-80268.html'),
    ('Smoking Hot Refill', 'https://www.fragrantica.com/perfume/Robbie-VanGogh/Matau-12684.html'),
    ('Rosa', 'https://www.fragrantica.com/perfume/House-of-BO/Rosario-78779.html'),
    ('Pour Homme Dylan Blue Eau de Toiletries', 'https://www.fragrantica.com/perfume/Versace/Versace-Pour-Homme-Dylan-Blue-40031.html'),
    ('Eau de Memo', 'https://www.fragrantica.com/perfume/Memo-Paris/Eau-de-Memo-44229.html'),
    ('Aqua Allegoria Bergamot Calabria', 'https://www.fragrantica.com/perfume/Guerlain/Aqua-Allegoria-Bergamote-Calabria-43596.html'),
    ('Gentleman Intense', 'https://www.fragrantica.com/perfume/Givenchy/Gentleman-Eau-de-Toilette-Intense-65051.html'),
    ('Champs-Élysées', 'https://www.fragrantica.com/perfume/Guerlain/Champs-Elysees-Eau-de-Parfum-67312.html'),
    ('Poison Girl', 'https://www.fragrantica.com/perfume/Dior/Poison-Girl-35561.html'),
    ('Joy by Dior', 'https://www.fragrantica.com/perfume/Dior/Joy-by-Dior-51285.html'),
    ('Guilty Pour Homme', 'https://www.fragrantica.com/perfume/Gucci/Guilty-Pour-Homme-11037.html'),
    ('La Nuit Trésor', 'https://www.fragrantica.com/perfume/Lancome/La-Nuit-Tresor-29157.html'),
    ('Good Girl Gone Bad Extreme', 'https://www.fragrantica.com/perfume/By-Kilian/Good-Girl-Gone-Bad-Extreme-43810.html'),
    ("D'En Le Bleu Que Petit", 'https://www.fragrantica.com/perfume/Serge-Lutens/Dans-Le-Bleu-Qui-Petille-74024.html'),
    ('Sacred Wood Refill', 'https://www.fragrantica.com/perfume/By-Kilian/Sacred-Wood-23897.html'),
    ('Fahrenheit Perfume', 'https://www.fragrantica.com/perfume/Dior/Fahrenheit-32-987.html'),
    ('Hero for Men', 'https://www.fragrantica.com/perfume/JAFRA/Legend-Hero-for-Men-44676.html'),
    ('Colonia Futura', 'https://www.fragrantica.com/perfume/Acqua-di-Parma/Colonia-Futura-62332.html'),
    ('Eau de Nuits', 'https://www.fragrantica.com/perfume/Keiko-Mecheri/Les-Nuits-D-Izu-9483.html'),
    ('Lamborghini', 'https://www.fragrantica.com/perfume/Jequiti/Lamborghini-46227.html'),
    ('Costa Azura', 'https://www.fragrantica.com/perfume/Van-Gils/His-Aura-by-Night-5622.html'),
    ('Soleil de Fou', 'https://www.fragrantica.com/perfume/Etat-Libre-d-Orange/Une-Amourette-Roland-Mouret-46517.html'),
    ('Opium', 'https://www.fragrantica.com/perfume/Yves-Saint-Laurent/Opium-Eau-de-Parfum-2009-7399.html'),
    ('Diorissimo', 'https://www.fragrantica.com/perfume/Dior/Diorissimo-224.html'),
    ('Miss Dior Rose & Roses Roller Pearl', 'https://www.fragrantica.com/perfume/Dior/Miss-Dior-Rose-N-Roses-Roller-Pearl-65505.html'),
    ('Rive Gauche', 'https://www.fragrantica.com/perfume/Yves-Saint-Laurent/Rive-Gauche-96.html'),
    ('Mon Guerlain Intense', 'https://www.fragrantica.com/perfume/Fragrance-World/Mon-Gracieuse-Parfum-Intense-104233.html'),
    ('Love Story', 'https://www.fragrantica.com/perfume/Chloe/Love-Story-26227.html'),
    ('Aqua Vite', 'https://www.fragrantica.com/perfume/Oneiros/Aquavite-102982.html'),
    ('Jannat', 'https://www.fragrantica.com/perfume/Memo-Paris/Jannat-5048.html'),
    ('Youth Duo', 'https://www.fragrantica.com/perfume/Maison-d-ETTO/Verdades-97105.html'),
    ('Aqua Allegoria Pera Granita', 'https://www.fragrantica.com/perfume/Guerlain/Aqua-Allegoria-Pera-Granita-35554.html'),
    ('Black Opium Le Parfum', 'https://www.fragrantica.com/perfume/Yves-Saint-Laurent/Black-Opium-Le-Parfum-78427.html'),
    ('Citrus Bigarade', 'https://www.fragrantica.com/perfume/Creed/Citrus-Bigarade-63619.html'),
    ('Nomade Nuit de Egypt', 'https://www.fragrantica.com/perfume/Chloe/Nomade-Nuit-d-Egypte-89372.html'),
    ('Modern Muse', 'https://www.fragrantica.com/perfume/Estee-Lauder/Modern-Muse-18319.html'),
    ('For Her Musk Noir', 'https://www.fragrantica.com/perfume/Narciso-Rodriguez/Musc-Noir-Rose-For-Her-71596.html'),
    ('Aqua Allegoria Eau de Euju Forte', 'https://www.fragrantica.com/perfume/Guerlain/Aqua-Allegoria-Herba-Fresca-60.html'),
    ('Love Shot', 'https://www.fragrantica.com/perfume/Ex-Nihilo/Love-Shot-35810.html'),
    ('Luna Rosa Ocean', 'https://www.fragrantica.com/perfume/Prada/Luna-Rossa-Ocean-68753.html'),
    ('Omnia Coral', 'https://www.fragrantica.com/perfume/Bvlgari/Omnia-Coral-14297.html'),
    ('Peunotic Poison', 'https://www.fragrantica.com/perfume/Nobile-1942/Il-Capriccio-del-Maestro-49195.html'),
    ('Crystal Noir', 'https://www.fragrantica.com/perfume/Versace/Crystal-Noir-631.html'),
    ('Bois Marocain', 'https://www.fragrantica.com/perfume/Tom-Ford/Bois-Marocain-2022-79014.html'),
    ('Aqua Allegoria Flora Bloom', 'https://www.fragrantica.com/perfume/Guerlain/Aqua-Allegoria-Florabloom-Forte-89855.html'),
    ('Pour Monsieur', 'https://www.fragrantica.com/perfume/Chanel/Pour-Monsieur-615.html'),
    ("Jour d'Hermes", 'https://www.fragrantica.com/perfume/Hermes/Jour-d-Hermes-17076.html'),
    ('Chance Eau Vive', 'https://www.fragrantica.com/perfume/Chanel/Chance-Eau-Vive-30796.html'),
    ('Dublevé.te.', None),
    ('Eau de Ombré Leather', 'https://www.fragrantica.com/perfume/Fragrance-World/Cuir-Leather-Parfum-109252.html'),
    ('Atelier de Fleurs Herba Mimosa', 'https://www.fragrantica.com/perfume/Kierin/Pier-NY-69897.html'),
    ('No. 5 Refill', 'https://www.fragrantica.com/perfume/Victorio-Lucchino/No-5-Jazmim-Exotico-40568.html'),
    ('White Linen', 'https://www.fragrantica.com/perfume/Estee-Lauder/White-Linen-542.html'),
    ('Couros', 'https://www.fragrantica.com/perfume/Granado/Couro-62820.html'),
    ('Higher Energy', 'https://www.fragrantica.com/perfume/Dior/Higher-Energy-234.html'),
    ('Pleasure Intense', 'https://www.fragrantica.com/perfume/Enima-Rocca/Huracan-103696.html'),
    ('Jasmine et Cigarette', 'https://www.fragrantica.com/perfume/Etat-Libre-d-Orange/Jasmin-et-Cigarette-4518.html'),
    ('Beautiful', 'https://www.fragrantica.com/perfume/Estee-Lauder/Beautiful-528.html'),
    ('No. 5 Perfume Refill Portable Spray', 'https://www.fragrantica.com/perfume/Puredistance/Antonia-No-02-10720.html'),
    ('Bloom Ambrosia di Fiori', 'https://www.fragrantica.com/perfume/Gucci/Gucci-Bloom-Ambrosia-di-Fiori-57355.html'),
    ('Nomade Jasmine Naturale Intense', 'https://www.fragrantica.com/perfume/Chloe/Nomade-Jasmin-Naturel-Intense-79230.html'),
    ('Devil Tender', 'https://www.fragrantica.com/perfume/Ex-Nihilo/Devil-Tender-41266.html'),
    ('Honeysuckle and Davana', 'https://www.fragrantica.com/perfume/Illamasqua/Freak-Scarab-21724.html'),
    ('Tuberose Criminal', 'https://www.fragrantica.com/perfume/Serge-Lutens/Tubereuse-Criminelle-5200.html'),
    ('Silver Birch and Lavender', 'https://www.fragrantica.com/perfume/Shay-Blue-London/Pineapple-Ice-109839.html'),
    ('Eau Navati', 'https://www.fragrantica.com/perfume/Diptyque/Eau-Nabati-80355.html'),
    ('La Femme Prada', 'https://www.fragrantica.com/perfume/Prada/Prada-L-Homme-39029.html'),
    ('Man Wood Essence', 'https://www.fragrantica.com/perfume/Bvlgari/Bvlgari-Man-Wood-Essence-50602.html'),
    ('Aqua Celestia', 'https://www.fragrantica.com/perfume/Maison-Francis-Kurkdjian/Aqua-Celestia-42268.html'),
    ('Aqua Allegoria Rosa Pallisandro Forte', 'https://www.fragrantica.com/perfume/Guerlain/Aqua-Allegoria-Forte-Rosa-Palissandro-83015.html'),
    ('Silver Birch & Lavender', 'https://www.fragrantica.com/perfume/Jo-Malone-London/Silver-Birch-Lavender-Cologne-59427.html'),
    ("J'adore", 'https://www.fragrantica.com/perfume/Dior/J-adore-210.html'),
    ('Renaissance', 'https://www.fragrantica.com/perfume/TUMI/Renaissance-97063.html'),
    ('Dune Pour Homme', 'https://www.fragrantica.com/perfume/Dior/Dune-Pour-Homme-235.html'),
    ('Win Ple de Cassie', 'https://www.fragrantica.com/perfume/Lush/Tuca-Tuca-9451.html'),
    ('For Her Musk Nude', 'https://www.fragrantica.com/perfume/Narciso-Rodriguez/Narciso-Rodriguez-For-Her-Musc-Nude-88936.html'),
    ('Chloe', 'https://www.fragrantica.com/perfume/Chloe/Chloe-Eau-de-Parfum-1733.html'),
    ('Green Almond & Redcurrant Cologne', 'https://www.fragrantica.com/perfume/Jo-Malone-London/Green-Almond-Redcurrant-Cologne-2023-87709.html'),
    ('No. 5 Twist & Spray Refill Set', 'https://www.fragrantica.com/perfume/Estee-Lauder/Modern-Muse-Le-Rouge-31293.html'),
    ("L'Eau Réves d'Elias", 'https://www.fragrantica.com/perfume/L-Eau-De-Cassis/Reves-De-Cassis-65281.html'),
    ('Iris (Medici Garden Collection)', 'https://www.fragrantica.com/perfume/Salvatore-Ferragamo/Viola-Essenziale-2013-20590.html'),
    ('Man in Black', 'https://www.fragrantica.com/perfume/Votre-Parfum/Man-in-Black-54563.html'),
    ('Dior Homme Sport', 'https://www.fragrantica.com/perfume/Dior/Dior-Homme-Sport-2021-71326.html'),
    ('Bronze Goddess Eau Fresh', 'https://www.fragrantica.com/perfume/Estee-Lauder/Bronze-Goddess-L-Eau-de-Lumiere-79231.html'),
    ('Opium', 'https://www.fragrantica.com/perfume/Yves-Saint-Laurent/Opium-Eau-de-Parfum-2009-7399.html'),
    ('No. 5 Refill Portable Spray', 'https://www.fragrantica.com/perfume/Puredistance/Antonia-No-02-10720.html'),
    ('Issia La Nuit', 'https://www.fragrantica.com/perfume/Imaginary-Authors/Whispered-Myths-47333.html'),
    ('Cur Moresque', 'https://www.fragrantica.com/perfume/Moresque/Sandal-Granada-44325.html'),
    ('Cie Passion Eclat', 'https://www.fragrantica.com/perfume/Shulton-Company/CIE-by-Jacqueline-Cochran-38292.html'),
    ('Nomade Jasmine Naturale', 'https://www.fragrantica.com/perfume/Chloe/Nomade-48434.html'),
    ('E.Q.', 'https://www.fragrantica.com/perfume/Hermes/Equipage-7.html'),
    ('No. 5 Perfume Refill', 'https://www.fragrantica.com/perfume/Chanel/Chanel-No-5-Parfum-28711.html'),
    ('Chloé Signature Naturelle Intense', 'https://www.fragrantica.com/perfume/Chloe/Chloe-Eau-de-Parfum-Naturelle-68777.html'),
    ('Miss Dior Roller Pearl', 'https://www.fragrantica.com/perfume/Dior/Miss-Dior-Blooming-Bouquet-Roller-Pearl-48407.html'),
    ('Champs-Élysées', 'https://www.fragrantica.com/perfume/Guerlain/Champs-Elysees-Eau-de-Parfum-67312.html'),
    ('Knowing', 'https://www.fragrantica.com/perfume/Estee-Lauder/Knowing-548.html'),
    ('Zagara', 'https://www.fragrantica.com/perfume/Monotheme-Venezia/Zagara-15627.html'),
    ('Armani Code', 'https://www.fragrantica.com/perfume/Giorgio-Armani/Armani-Code-Parfum-75126.html'),
    ('Atelier des Fleurs Narcissus Poeticus', 'https://www.fragrantica.com/perfume/Chloe/Narcissus-Poeticus-69293.html'),
    ('Allure Sensual', 'https://www.fragrantica.com/perfume/House-of-Brandt/Bois-de-Santal-89216.html'),
    ('Bergamot', 'https://www.fragrantica.com/perfume/Le-Labo/Bergamote-22-6327.html'),
    ('Bouquet de Ongri', 'https://www.fragrantica.com/perfume/Ermetiche-Fragranze/Oniricum-89779.html'),
    ('My Way Perfume', 'https://www.fragrantica.com/perfume/Nimere-Parfums/Dragon-Blood-Cuir-Vermillion-48324.html'),
    ('Crystal', 'https://www.fragrantica.com/perfume/ALT-Fragrances/Crystal-86958.html'),
    ('Patchouli', 'https://www.fragrantica.com/perfume/Essential-Parfums/Patchouli-Mania-85144.html'),
    ('Honeysuckle Anne Davana Gift Package', 'https://www.fragrantica.com/perfume/Jo-Malone-London/Honeysuckle-Davana-51266.html'),
    ('Amiris Homme', 'https://www.fragrantica.com/perfume/Maison-Francis-Kurkdjian/Amyris-Homme-15566.html'),
    ('Eau de Basilic Poufre', 'https://www.fragrantica.com/perfume/Rochas/Eau-de-Rochas-Escapade-Au-Soleil-59872.html'),
    ('Chloe Lumines', 'https://www.fragrantica.com/perfume/Chloe/Chloe-L-Eau-de-Parfum-Lumineuse-83915.html'),
    ('Cie Passion', 'https://www.fragrantica.com/perfume/Shulton-Company/CIE-by-Jacqueline-Cochran-38292.html'),
    ('Emme.A.', 'https://www.fragrantica.com/perfume/Burdin/Emmene-Moi-67200.html'),
    ('Lavanda Imperiale', 'https://www.fragrantica.com/perfume/Santa-Maria-Novella/Lavanda-Imperiale-11469.html'),
    ('Aqua Allegoria Florabloom', 'https://www.fragrantica.com/perfume/Guerlain/Aqua-Allegoria-Florabloom-Forte-89855.html'),
    ('Hundred Silent Ways Extra de Parfum', 'https://www.fragrantica.com/perfume/Nishane/Hundred-Silent-Ways-37602.html'),
    ('Black Opium Extreme', 'https://www.fragrantica.com/perfume/Yves-Saint-Laurent/Black-Opium-Extreme-68506.html'),
    ('Coco Refill', 'https://www.fragrantica.com/perfume/Cacharel/Ella-Ella-101823.html'),
    ('Fumerie Türk', 'https://www.fragrantica.com/perfume/Serge-Lutens/Fumerie-Turque-2765.html'),
    ('Cannabis', 'https://www.fragrantica.com/perfume/Bois-1920/Cannabis-Fruttata-54935.html'),
    ("Eau d'Orange Berthe", 'https://www.fragrantica.com/perfume/Chloe/Love-Story-Eau-Sensuelle-42130.html'),
    ('Je.A.', 'https://www.fragrantica.com/perfume/Maison-Alhambra/Jean-Lowe-Immortal-83666.html'),
    ('Italian Leather', 'https://www.fragrantica.com/perfume/Memo-Paris/Italian-Leather-21771.html'),
    ('Guilty Pour Homme', 'https://www.fragrantica.com/perfume/Gucci/Guilty-Pour-Homme-11037.html'),
    ('Solaris', 'https://www.fragrantica.com/perfume/Penhaligon-s/Solaris-81413.html'),
    ('Mughetto', 'https://www.fragrantica.com/perfume/Santa-Maria-Novella/Mughetto-17979.html'),
    ('English Pear & Sweet Pea Special Edition', 'https://www.fragrantica.com/perfume/Jo-Malone-London/English-Pear-Sweet-Pea-84035.html'),
    ('Jasmine 17 (Bulk)', 'https://www.fragrantica.com/perfume/Giardino-Magico/Jasmine-Cassis-83346.html'),
    ('Idol', 'https://www.fragrantica.com/perfume/French-Attitude/Idol-47531.html'),
    ('Poison', 'https://www.fragrantica.com/perfume/Dior/Poison-218.html'),
    ("Pew d'Espagne", 'https://www.fragrantica.com/perfume/DSH-Perfumes/Mon-Petit-Oiseau-113333.html'),
    ('Portrait Changing Constance', 'https://www.fragrantica.com/perfume/Penhaligon-s/Changing-Constance-50256.html'),
    ('Gentleman Reserve Privé', 'https://www.fragrantica.com/perfume/Givenchy/Gentleman-Eau-de-Parfum-Reserve-Privee-71272.html'),
    ('Aqua Allegoria Flora Salvage', 'https://www.fragrantica.com/perfume/Guerlain/Aqua-Allegoria-Flora-Salvaggia-66359.html'),
    ('Gold Night Refill', 'https://www.fragrantica.com/perfume/By-Far/Daydream-of-a-Love-Trance-80203.html'),
    ('Miss Dior Original', 'https://www.fragrantica.com/perfume/Dior/Miss-Dior-Original-Extrait-de-Parfum-26209.html'),
    ('Coco Mademoiselle', 'https://www.fragrantica.com/perfume/Chanel/Coco-Mademoiselle-611.html'),
    ('Eau de Privé Collection', 'https://www.fragrantica.com/perfume/Giorgio-Armani/Iris-Celadon-42886.html'),
    ('Winter Palace', 'https://www.fragrantica.com/perfume/Memo-Paris/Winter-Palace-55377.html'),
    ('Eau Sauvage', 'https://www.fragrantica.com/perfume/Dior/Eau-Sauvage-231.html'),
    ('Wind Flowers', 'https://www.fragrantica.com/perfume/Creed/Wind-Flowers-70182.html'),
    ('Dublevé.te', None),
    ('Trésor', 'https://www.fragrantica.com/perfume/Lancome/Tresor-172.html'),
    ('Cee Intense', 'https://www.fragrantica.com/perfume/Pont-Des-Arts/Jardin-des-Avelines-100605.html'),
    ('G.E.', 'https://www.fragrantica.com/perfume/Givenchy/Gentleman-Eau-de-Parfum-Reserve-Privee-71272.html'),
    ("Foujer d'Argent", 'https://www.fragrantica.com/perfume/Miraj/Fujer-81754.html'),
    ('Wild Bluebell Gift Package', 'https://www.fragrantica.com/perfume/Jo-Malone-London/Wild-Bluebell-12310.html'),
    ('Unsung Précieux', 'https://www.fragrantica.com/perfume/Laverne/Musk-Patchouli-70106.html'),
    ('Ombré Leather Perfume', 'https://www.fragrantica.com/perfume/Grace-de-Monaco/Ombre-Sereine-85314.html'),
    ('Violet & Amber Absolute', 'https://www.fragrantica.com/perfume/Estee-Lauder/White-Linen-Oud-Legacy-104933.html'),
    ('Issia', 'https://www.fragrantica.com/perfume/Parfums-Dusita/Issara-36485.html'),
    ('Cara Rosa', 'https://www.fragrantica.com/perfume/Etienne-Aigner/Cara-Mia-Ti-Amo-43323.html'),
    ('Eau de Lancome', 'https://www.fragrantica.com/perfume/Lancome/La-Nuit-Tresor-Caresse-40086.html'),
    ('Psychedelic Love', 'https://www.fragrantica.com/perfume/Initio-Parfums-Prives/Psychedelic-Love-45977.html'),
    ('La Vie Belle Rose Extraordinaire', 'https://www.fragrantica.com/perfume/Lancome/La-Vie-Est-Belle-Rose-Extraordinaire-89903.html'),
    ('Eau de Pamplemousse Rose', 'https://www.fragrantica.com/perfume/Hermes/Eau-de-Pamplemousse-Rose-6064.html'),
    ("Can't Stop Loving You Refill", 'https://www.fragrantica.com/perfume/By-Kilian/Can-t-Stop-Loving-You-78735.html'),
    ('No. 5 Refill', 'https://www.fragrantica.com/perfume/Victorio-Lucchino/No-5-Jazmim-Exotico-40568.html'),
    ('Eva', 'https://www.fragrantica.com/perfume/Santa-Maria-Novella/Eva-11421.html'),
    ('Mimosa & Cardamom', 'https://www.fragrantica.com/perfume/Jo-Malone-London/Mimosa-Cardamom-31825.html'),
    ('Bois Diris', 'https://www.fragrantica.com/perfume/Van-Cleef-Arpels/Bois-d-Iris-6466.html'),
    ('Artemisia', 'https://www.fragrantica.com/perfume/Penhaligon-s/Artemisia-4547.html'),
    ('Irresistible Rose Velvet', 'https://www.fragrantica.com/perfume/Givenchy/Irresistible-Givenchy-Rose-Velvet-78480.html'),
    ('Zapperano', 'https://www.fragrantica.com/perfume/Acqua-di-Parma/Zafferano-73365.html'),
    ('Imbré', 'https://www.fragrantica.com/perfume/Eudora/Impression-in-Black-54531.html'),
    ('La Vie Belle', 'https://www.fragrantica.com/perfume/Lancome/La-Vie-Est-Belle-14982.html'),
    ('All of Me', 'https://www.fragrantica.com/perfume/Narciso-Rodriguez/All-Of-Me-84201.html'),
    ('Bamboo', 'https://www.fragrantica.com/perfume/By-Kilian/Bamboo-Harmony-14330.html'),
    ('Portrait the Uncompromising Sohan', 'https://www.fragrantica.com/perfume/Penhaligon-s/The-Uncompromising-Sohan-46503.html'),
    ('Musk Therapy Extrait de Parfum', 'https://www.fragrantica.com/perfume/Veld-s/Prends-Moi-16004.html'),
    ('Rose Gold Intense', 'https://www.fragrantica.com/perfume/Tiffany/Tiffany-Co-Rose-Gold-Intense-84788.html'),
    ('Portrait Terrible Teddy', 'https://www.fragrantica.com/perfume/Penhaligon-s/Terrible-Teddy-55441.html'),
    ('Patchouli 24', 'https://www.fragrantica.com/perfume/Le-Labo/Patchouli-24-6332.html'),
    ('Moon Fever', 'https://www.fragrantica.com/perfume/Memo-Paris/Moon-Fever-28141.html'),
    ('Annie Extrait de Parfum', 'https://www.fragrantica.com/perfume/Lancome/La-Vie-Est-Belle-L-Extrait-de-Parfum-34040.html'),
    ('Le Homme', 'https://www.fragrantica.com/perfume/Milestone-Perfumes/Grandeur-Le-Homme-110387.html'),
    ("L'Antérieur Rouge Ultim", 'https://www.fragrantica.com/perfume/Pierre-Guillaume-Paris/Interieur-Nuit-45278.html'),
    ('My Way Floral', 'https://www.fragrantica.com/perfume/Giorgio-Armani/My-Way-Floral-73284.html'),
    ('Soir de Lune', 'https://www.fragrantica.com/perfume/Sisley/Soir-de-Lune-605.html'),
    ('Addictive Vibration', 'https://www.fragrantica.com/perfume/Initio-Parfums-Prives/Addictive-Vibration-38666.html'),
    ('Tuberosa', 'https://www.fragrantica.com/perfume/Granado/Tuberosa-96623.html'),
    ('Portrait Much Ado About the Duke', 'https://www.fragrantica.com/perfume/Penhaligon-s/Much-Ado-About-The-Duke-40713.html'),
    ('Poudre', 'https://www.fragrantica.com/perfume/Jeja-Parfum/Poudre-105132.html'),
    ('Soleil Brulent', 'https://www.fragrantica.com/perfume/Tom-Ford/Soleil-Brulant-66125.html'),
    ("J'adore Roller Pearl", 'https://www.fragrantica.com/perfume/Dior/J-Adore-Roller-Pearl-53834.html'),
    ("J'adore Roller Pearl", 'https://www.fragrantica.com/perfume/Dior/J-Adore-Roller-Pearl-53834.html'),
    ('312 Saint-Honoré', 'https://www.fragrantica.com/perfume/BDK-Parfums/312-Saint-Honore-89642.html'),
    ('24 Faubourg', 'https://www.fragrantica.com/perfume/Hermes/24-Faubourg-27.html'),
    ('Luxo Wood', 'https://www.fragrantica.com/perfume/Aromatix-X-French-Avenue/Royal-Taboo-99330.html'),
    ('Te.G.', 'https://www.fragrantica.com/perfume/Novaa-Zara-The-New-Dawn/Extrait-Magnolia-de-Soukhoum-TEGE-67912.html'),
    ('Maresiala', 'https://www.fragrantica.com/perfume/Santa-Maria-Novella/Marescialla-11479.html'),
    ('Metalique', 'https://www.fragrantica.com/perfume/Tom-Ford/Metallique-55766.html'),
    ('Ocean Leather', 'https://www.fragrantica.com/perfume/Memo-Paris/Ocean-Leather-60587.html'),
    ('Rose on Ice Refill', 'https://www.fragrantica.com/perfume/By-Kilian/Roses-on-Ice-62616.html'),
    ('Guilty Intense Pour Femme', 'https://www.fragrantica.com/perfume/Gucci/Gucci-Guilty-Eau-de-Parfum-Intense-Pour-Femme-71377.html'),
    ('Guilty Pour Femme', 'https://www.fragrantica.com/perfume/Gucci/Guilty-Elixir-de-Parfum-pour-Homme-84547.html'),
    ('G.E.R.', 'https://www.fragrantica.com/perfume/Frederic-Malle/Geranium-Pour-Monsieur-5911.html'),
    ('Crystal', 'https://www.fragrantica.com/perfume/ALT-Fragrances/Crystal-86958.html'),
    ('Idol Now', 'https://www.fragrantica.com/perfume/Lancome/Idole-Now-81792.html'),
    ('Armani Code Femme', 'https://www.fragrantica.com/perfume/Giorgio-Armani/Armani-Code-Absolu-Femme-54302.html'),
    ('Magnetic Blend 7', 'https://www.fragrantica.com/perfume/Initio-Parfums-Prives/Magnetic-Blend-7-30995.html'),
    ('Addict', 'https://www.fragrantica.com/perfume/Initio-Parfums-Prives/Addictive-Vibration-38666.html'),
    ('Strawberry', 'https://www.fragrantica.com/perfume/Phlur/Strawberry-Letter-89909.html'),
    ('Tiffany Sheer', 'https://www.fragrantica.com/perfume/Tiffany/Tiffany-Co-Sheer-53062.html'),
    ('Elixir de Mervaille', 'https://www.fragrantica.com/perfume/Hermes/Elixir-des-Merveilles-3168.html'),
    ('Lusa', 'https://www.fragrantica.com/perfume/Oakcha/Garden-of-Lusail-92995.html'),
    ('La Vie Belle Iris Absolute', 'https://www.fragrantica.com/perfume/Lancome/La-Vie-Est-Belle-L-Absolu-25727.html'),
    ('Zest Mandarin', 'https://www.fragrantica.com/perfume/Cafe-Parfums/Cafe-Green-5751.html'),
    ('Joy by Dior Intense', 'https://www.fragrantica.com/perfume/Dior/Joy-by-Dior-Intense-56214.html'),
    ('Coco Mademoiselle Eau de Toiletry Refill Spray', 'https://www.fragrantica.com/perfume/Chanel/Coco-Mademoiselle-Eau-de-Toilette-612.html'),
    ('Atelier de Fleurs Hibiscus Abelmoscus', 'https://www.fragrantica.com/perfume/Chloe/Hibiscus-Abelmoschus-57254.html'),
    ('Legacy of Petra', 'https://www.fragrantica.com/perfume/Penhaligon-s/Legacy-of-Petra-75584.html'),
    ('For Her Musk Noir Rose', 'https://www.fragrantica.com/perfume/Narciso-Rodriguez/Musc-Noir-Rose-For-Her-71596.html'),
    ('Hero for Men', 'https://www.fragrantica.com/perfume/JAFRA/Legend-Hero-for-Men-44676.html'),
    ('Blackberry & Bay Gift Package', 'https://www.fragrantica.com/perfume/Victoria-s-Secret/Velvet-Amber-Blackberry-7138.html'),
    ('Tabac Rose', 'https://www.fragrantica.com/perfume/BDK-Parfums/Tabac-Rose-61838.html'),
    ('High Frequency', 'https://www.fragrantica.com/perfume/Initio-Parfums-Prives/High-Frequency-42259.html'),
    ('Luna Rossa', 'https://www.fragrantica.com/perfume/Prada/Luna-Rossa-Black-48682.html'),
    ('Irresistible', 'https://www.fragrantica.com/perfume/Alkemia-Perfumes/Irresistible-54095.html'),
    ('Chloe Signature Naturalelle Intense', 'https://www.fragrantica.com/perfume/Chloe/Chloe-Eau-de-Parfum-Naturelle-68777.html'),
    ('Aqua Allegoria Granada Salvia', 'https://www.fragrantica.com/perfume/Guerlain/Aqua-Allegoria-Granada-Salvia-58966.html'),
    ('Opoponax', 'https://www.fragrantica.com/perfume/Olibanum/Opoponax-74696.html'),
    ('Inverness', 'https://www.fragrantica.com/perfume/Memo-Paris/Inverness-83482.html'),
    ('French Bouquet', 'https://www.fragrantica.com/perfume/BDK-Parfums/French-Bouquet-61837.html'),
    ('Grapefruit', 'https://www.fragrantica.com/perfume/Jo-Malone-London/Grapefruit-5584.html'),
    ('Legendary Mitsuko', 'https://www.fragrantica.com/perfume/Guerlain/Mitsouko-Eau-de-Parfum-113910.html'),
    ('Mystic Experience', 'https://www.fragrantica.com/perfume/Initio-Parfums-Prives/Mystic-Experience-30992.html'),
    ('Miu Miu Twist', 'https://www.fragrantica.com/perfume/Miu-Miu/Miu-Miu-Twist-53147.html'),
    ('Red Rose', 'https://www.fragrantica.com/perfume/Jo-Malone-London/Red-Roses-5484.html'),
    ('Eau de Ombre Leather', 'https://www.fragrantica.com/perfume/Fragrance-World/Cuir-Leather-Parfum-109252.html'),
    ('Periuthmon Boater', None),
    ("Miu Miu L'Oise", 'https://www.fragrantica.com/perfume/Miu-Miu/Miu-Miu-31468.html'),
    ('Lalibela', 'https://www.fragrantica.com/perfume/Memo-Paris/Lalibela-2783.html'),
    ('Pan Your Flames Extraté de Parfum', 'https://www.fragrantica.com/perfume/Etat-Libre-d-Orange/Story-of-Your-Life-97060.html'),
    ('Pleasure for Men', 'https://www.fragrantica.com/perfume/Fragrance-Du-Bois/Minuit-et-Demi-66071.html'),
    ('For Her Forever', 'https://www.fragrantica.com/perfume/Narciso-Rodriguez/Narciso-Rodriguez-For-Her-Forever-78835.html'),
    ('Dolce Vita', 'https://www.fragrantica.com/perfume/Dior/Dolce-Vita-222.html'),
    ('Coco Mademoiselle Eau Toilette Refill Spray', 'https://www.fragrantica.com/perfume/Chanel/Coco-Mademoiselle-Eau-de-Toilette-612.html'),
    ('Les Joss-à-la-Mode Lost in Grace', None),
    ('Miu Miu', 'https://www.fragrantica.com/perfume/Miu-Miu/Miu-Miu-31468.html'),
    ('Cee', 'https://www.fragrantica.com/perfume/RAER-Scents/Berlin-Collective-Scent-77909.html'),
    ('Tuberosa Extra de Parfum', 'https://www.fragrantica.com/perfume/Nina-Ricci/Nina-Le-Parfum-83150.html'),
    ('Eau Sauvage Extreme Intense', 'https://www.fragrantica.com/perfume/Dior/Eau-Sauvage-Extreme-2010-72771.html'),
    ('Diorella', 'https://www.fragrantica.com/perfume/Dior/Diorella-226.html'),
    ('Chams Eau de', 'https://www.fragrantica.com/perfume/Guerlain/Shalimar-Edition-Charms-Eau-de-Parfum-8140.html'),
    ("L'Eves d'Carre", 'https://www.fragrantica.com/perfume/Darren-Alan-Perfumes/After-The-Rain-87672.html'),
    ('24 Faubourg', 'https://www.fragrantica.com/perfume/Hermes/24-Faubourg-27.html'),
    ('Cannabis Perfume Oil', 'https://www.fragrantica.com/perfume/Malin-Goetz/Cannabis-Perfume-Oil-28705.html'),
    ('No. 5 Refill Spray', 'https://www.fragrantica.com/perfume/Puredistance/Antonia-No-02-10720.html'),
    ("L'Eves Daria", 'https://www.fragrantica.com/perfume/Manila-Grace/Manila-Grace-Fleur-Narcotique-41637.html'),
    ('La Vie Belle Soleil Crystal', 'https://www.fragrantica.com/perfume/Lancome/La-Vie-Est-Belle-Soleil-Cristal-65156.html'),
    ("Soars d'Orient", 'https://www.fragrantica.com/perfume/Rabanne/Lady-Million-9045.html'),
    ("Soars d'Orient", 'https://www.fragrantica.com/perfume/Rabanne/Lady-Million-9045.html'),
    ('Dark Rum Perfume Oil', 'https://www.fragrantica.com/perfume/Solstice-Scents/Island-Blackstrap-56187.html'),
    ('Higher', 'https://www.fragrantica.com/perfume/Dior/Higher-233.html'),
    ('Leather Perfume Oil', 'https://www.fragrantica.com/perfume/DS-Durga/Foxhunt-10233.html'),
    ('Escale Portofino', 'https://www.fragrantica.com/perfume/Dior/Cruise-Collection-Escale-a-Portofino-3291.html'),
    ('Cinnabar', 'https://www.fragrantica.com/perfume/Estee-Lauder/Cinnabar-546.html'),
    ('Twist', 'https://www.fragrantica.com/perfume/AXE/Twist-29884.html'),
    ('Eau Fresh', 'https://www.fragrantica.com/perfume/Jacques-Bogart/Eau-Fresh-9625.html'),
    ('Idol Aura', 'https://www.fragrantica.com/perfume/Cursed/Kill-For-Me-88691.html'),
    ('Sensuous', 'https://www.fragrantica.com/perfume/Estee-Lauder/Sensuous-2938.html'),
    ('Magic Noir', 'https://www.fragrantica.com/perfume/Lancome/Magie-Noire-174.html'),
    ('Pretnotic Poison Roller Pearl', None),
    ('Brain Dead X Cannabis Perfume Oil Limited Edition', 'https://www.fragrantica.com/perfume/Ataraxia-Perfumery/Vestibule-100362.html'),
    ("L'Eau Réveis Design", 'https://www.fragrantica.com/perfume/Majda-Bekkali/Songe-pour-Elle-12280.html'),
    ('Aliage Sport', 'https://www.fragrantica.com/perfume/Estee-Lauder/Alliage-Sport-Spray-553.html'),
    ("J'adore Roller Pearl Infinissime", 'https://www.fragrantica.com/perfume/Dior/J-Adore-Roller-Pearl-53834.html'),
    ('Sea Refill', 'https://www.fragrantica.com/perfume/Fragonard/Ile-d-Amour-4963.html'),
    ('Dior Essence', 'https://www.fragrantica.com/perfume/Dior/Dioressence-225.html'),
    ('EST. Super', 'https://www.fragrantica.com/perfume/Mirum/Dominus-53138.html'),
]
